### ISSUE TITLE
GetType() returns the wrong type due to lack of element type information for arrays

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2056] opened 2016-11-11 15:41 UTC
### Expected

```
System.Int32[]
System.User[]
System.Array
```

### Actual

```
Array
Array
Array
```

### Steps To Reproduce

http://deck.net/690c6a3cb1929e3cc16244417e983bc9

```cs
public class Program
{
    public class User
    {
        //...
    }
    
    public static void Main()
    {
        Console.WriteLine(typeof(int[]).FullName); 
        Console.WriteLine(typeof(User[]).FullName); 
        Console.WriteLine(typeof(Array).FullName);
    }
}
```

**Comment by michaelcheers** [comment] 2016-11-23 13:06
Related to #1346.

**Comment by michaelcheers** [comment] 2016-11-23 13:08
Duplicate of #1347, point 4.

**Comment by LeonidVeriga** [comment] 2016-12-05 19:30
Yes, duplicate of #1347, point 4 - update https://github.com/bridgedotnet/Bridge/issues/1347#issuecomment-263328892 with a progress when fixed.

**Comment by geoffreymcgill** [comment] 2016-12-19 17:13
Related to #2051 and #2052.

**Comment by geoffreymcgill** [comment] 2016-12-19 17:29
This feature has been implemented and a pull request has been submitted. The feature is expected to be included in the Bridge 15.7 release.

**Closed** 2017-01-09 10:58 UTC
Labels: feature
