### ISSUE TITLE
Unexpected behavior of Type.ToString

### ISSUE THREAD

**Issue by shadow-cs** [bridgedotnet/Bridge#2326] opened 2017-02-04 08:56 UTC
`Type.ToString` should return fully qualified name (https://msdn.microsoft.com/en-us/library/system.type.tostring(v=vs.110).aspx).

### Steps To Reproduce

http://deck.net/37b4b4dfb411f246dc1ffee522b83e1d/top

```c#
public class App
{
    public static void Main()
    {
        Type type = typeof(int);
        Console.WriteLine(type);
    }
}
```

### Expected Result

`System.Int32`

### Actual Result

`function (){this.$initialize();...`

**Comment by LeonidVeriga** [comment] 2017-02-04 10:32
Hi @shadow-cs,

That seems to be a duplicate of #1242.

**Closed by LeonidVeriga** 2017-02-04 10:32 UTC
Labels: defect, duplicate
