### ISSUE TITLE
Broken cast operators with Template attribute

### ISSUE THREAD

**Issue by stopiccot** [bridgedotnet/Bridge#3588] opened 2018-05-18 14:30 UTC
In our project we have csharp bindings to playcanvas 3d web engine. We do that via external classes and Template attributes. Every 3d engine has 2d and 3d vectors. It's very common to cast 2d vectors to 3d ones by adding zero z component. It's also very common to cast 3d vectors to 2d vectors by dropping z component. Below you can see a very simple example of doing that by passing 2d vectors to function that works with 3d ones. Test1 does use implicit casting. Test2 does that explicitly.

### Steps To Reproduce

```csharp
using Bridge;

[External]
[Constructor("new pc.Vec2")]
public class Vector2
{
    public float x;
    public float y;

    [Template("new pc.Vec2({0}, {1})")]
    public extern Vector2(float x, float y);

    [Template("new pc.Vec3({0}.x, {0}.y, 0)")]
    public extern static implicit operator Vector3(Vector2 source);
}

[External]
[Constructor("new pc.Vec3")]
public class Vector3
{
    public float x;
    public float y;
    public float z;

    [Template("new pc.Vec3({0}, {1}, {2})")]
    public extern Vector3(float x, float y, float z);

    [Template("new pc.Vec2({0}.x, {0}.y)")]
    public extern static implicit operator Vector2(Vector3 source);
}

public class Utility
{
    public Vector3 F(Vector3 v) {
        return new Vector3(v.x + 1, v.y + 2, v.z + 3);
    }
}

public class Program
{
    public static void Test1() {
        var u = new Utility();
        Vector2 v0 = new Vector2(1, 1);
        Vector2 v1 = u.F(v0);
    }

    public static void Test2() {
        var u = new Utility();
        Vector2 v0 = new Vector2(1, 1);
        Vector3 v0_ = v0;
        Vector3 v1_ = u.F(v0_);
        Vector2 v1 = v0_;
    }

    public static void Main() {
        Test1();
        Test2();
    }
}
```
Sadly this result can't be compiled via deck.net. Gives me `System.Exception: ReferenceError: pc is not defined` error. But this can be done in empty bridge project.

### Code generated for Test1:
```js
Test1: function () {
    var u = new Utility();
    var v0 = new pc.Vec2(1, 1);
    var v1 = new pc.Vec2(new pc.Vec3(v0.x, v0.y, 0).x, new pc.Vec3(v0.x, v0.y, 0).y);
}
```

### Code generated for Test2:
```js
Test2: function () {
    var u = new Utility();
    var v0 = new pc.Vec2(1, 1);
    var v0_ = new pc.Vec3(v0.x, v0.y, 0);
    var v1_ = u.F(v0_);
    var v1 = new pc.Vec2(v0_.x, v0_.y);
}
```
Test1 code is obviously incorrect because there is no `u.F()` call at all.
Bug is reproducing for me while running both 16.5.0 and 17.0.0 Bridge versions. My guess is that all 16.x versions are affected too.

**Comment by AndreyChechel** [comment] 2018-05-18 15:28
Hi @stopiccot,

Looks like it's possible to work around the problem by using a named reference to the implicit operator argument. You can use that approach until the issue is fixed.

```cs
[External]
[Constructor("new pc.Vec3")]
public class Vector3
{
    // Revised [Template] attribute:
    [Template("new pc.Vec2({source}.x, {source}.y)")]
    public extern static implicit operator Vector2(Vector3 source);
}
```

This code is compiled to the following JavaScript (I guess it is what was expected):
```js
Test1: function () {
   var $t;
   var u = new Utility();
   var v0 = new pc.Vec2(1, 1);
   var v1 = ($t = u.F(new pc.Vec3(v0.x, v0.y, 0)), new pc.Vec2($t.x, $t.y));
}
```

**Comment by fabriciomurta** [comment] 2018-05-24 16:34
The fix has been merged last night to Bridge upstream branch! The fix will make it to the next Bridge release and you'll be able to use `{0}` in the template again! Thanks for reporting!
(next Bridge release is reflected in issue's milestone)

**Closed by fabriciomurta** 2018-05-24 16:34 UTC
Labels: defect
