### ISSUE TITLE
Design flaw with async Task / runCallbacks

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#3476] opened 2018-03-19 19:31 UTC
Implementation of async execution with use runCallbacks leads to unexpected 'multithread-like' behaviour due nondeterministic execution flow, which leads to data corruption.

I attached incomplete sample (excerpt from real complex project), but picturing important points

https://deck.net/4dce04131a637b83b1794f0a0cafdc53

If i.e. user-interface-event runs m1 method and another event runs m3 method it is possible sequence of execution:
enter m1
enter m3 
enter m4 (POINT2)
enter m2
return from m4 to m3 (POINT3)
m_bTestData is 'corrupted' here.

since runCallbacks  is called after every task completion, no one can determine sequence of execution.
this behaviour is not time dependent, but data dependent - in our real project m2 waits for TaskCompletionSource to be 'signaled' by second ui-event.

**Comment by geoffreymcgill** [comment] 2018-03-20 16:49
Hi @kosmab – Thanks for the report. We will investigate. 

Can you update your Deck to include some `Console.WriteLine` calls? We'll be able to see the actual output order, and you can also provide the expected output order of the calls.

**Comment by kosmab** [comment] 2018-03-20 17:07
Hi, async method is implemented as state machine where each step is separate task. let call whole async method as sequence - after every task completion is setTimeout called, which is new event and allows to assign 'time quant' to other task - not necessary continuation of just finished task - result is interleaved execution of task from two or more sequences - this construction is often called 'fibers' - very simmilar to multihreading execution - when unprotected - leads to data corruption. Probably its necessary to introduce concept of 'excecution context' and allow to switch context only at execution context end or when waiting for external world (i.e. ajax call).
I will try update Deck sample to show this effects

**Comment by kosmab** [comment] 2018-03-20 17:51
https://deck.net/cf5b409c535006ede510b75c23da4251

**Comment by geoffreymcgill** [comment] 2018-03-21 07:37
I spent some time cleaning up your sample and configured also run in native .NET so we can compare the results. The samples appear to still reproduce the issue from your original Deck, but please confirm. 

We will be investigating the defect.

https://deck.net/88a03f697de3f0ed90e2a1b4c5cbad69

https://dotnetfiddle.net/prGCn4

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

public class Program
{
    public static void Main()
    {
		temp.SomeEvent1();		
     
        Task.Delay(1000);
        
		temp.SomeEvent2();
    }     

    private static Temp temp = new Temp();
}

public class Temp
{ 
    public Temp()
    {
        testData = true;
        source = new TaskCompletionSource<object>();
    }
    
    public void SomeEvent1()
    {
        Method1().ContinueWith(
            r_=> {
            //something
        });
    }
	
    public void SomeEvent2()
    {        
        Method2().ContinueWith(
            r_=> {
            //something
        });
    }
    
    public async Task<string> Method1()
    {
        //wait for second click
        //BTW: remove this line and compiler will fail
        object oResult = await source.Task;
        
        //do some finishing
        return await Method4();
    }
    
    public async Task<string> Method2()
    {
        //wake up second activity
        source.SetResult(null);
        
   		//do some finishing
        return await Method3();
    }
    
    public async Task<string> Method3()
    {
        //call whatever
		await Method5();
        
        testData = false;
        
        return "";
   	}
    
    public async Task<string> Method4()
    {
        // Expected: True
        Console.WriteLine("P1 = " + testData.ToString());

        await Method5();
        
        // Expected: True
        Console.WriteLine("P2 = " + testData.ToString());
      
        return "";
   	}
    
    public async Task<string> Method5()
    {
        //any action - doesnt matter
		await Task.Run(() => DoSomething());
		
        return "";
    }
	
    static void DoSomething() { }
    
    bool testData;
	
    TaskCompletionSource<object> source;
}
```

**Comment by kosmab** [comment] 2018-03-21 08:26
Yes, it is correct.

The Method5 can be even simpler:

 

public Task<string> Method5()

{

        return Task.FromResult<string>("");

}

**Comment by geoffreymcgill** [comment] 2018-03-28 05:28
A PR fixing this issue has been submitted. Once final review and testing are complete, we will include in the upcoming Bridge 17.0 release. 

The [dev.deck.net](https://dev.deck.net) instance should be updated in the next day or so with the fix, so you'll be able to confirm the fix online. We'll post a message here when Deck is ready.

**Comment by geoffreymcgill** [comment] 2018-03-28 22:29
@kosmab – The sample from above is now working in Deck and available for your review, see

https://dev.deck.net/c181f842352d4329c4c9f8fa55833622

**Comment by fabriciomurta** [comment] 2018-03-28 22:33
The fix has just been accepted and merged up! The fix is already reflected to dev.deck.net: https://dev.deck.net/c181f842352d4329c4c9f8fa55833622

**Comment by fabriciomurta** [comment] 2018-03-28 22:35
The fix has been merged upstream and Deck updated, so dev.deck.net now reflects the fixed version of Bridge. As stated above, it will be available next Bridge release.

**Comment by geoffreymcgill** [comment] 2018-03-28 22:46
Now that this is fixed, I'm going to revise the title of this issue since we don't need to yell around here, and once this hits the release notes for 17.0, I don't really want to be looking at a line item like that.

**Comment by kosmab** [comment] 2018-03-29 07:09
Where can I find new bridge runtime (bridge.js)  - or better – prerelease NuGet package?

**Comment by geoffreymcgill** [comment] 2018-03-29 07:17
Bridge 17.0 is now based on the `dev` branch. 

https://github.com/bridgedotnet/Bridge/tree/dev

#### Build from source
https://github.com/bridgedotnet/Bridge/wiki/Build-From-Source

**Comment by kosmab** [comment] 2018-03-29 12:18
IMHO, it’s still bad:

 

https://dev.deck.net/cb3c4f2c94e3472a76a81d9d13c11566

**Comment by fabriciomurta** [comment] 2018-03-29 12:38
Can't say _"no, it is not"_ with such a proof. :)

Here's the code working in dotnet fiddle: https://dotnetfiddle.net/7LhpuH

**Comment by fabriciomurta** [comment] 2018-03-30 19:28
Okay, @kosmab! Just fixed this second scenario you presented. The fixed version is already available on dev.deck.net (just try your own deck URL, it should work now).

Additionally, also the issue with the commented out line is no more.
The fix will become available next Bridge release (see attached milestone).

**Closed by fabriciomurta** 2018-03-30 19:28 UTC
Labels: defect

**Comment by kosmab** [comment] 2018-03-30 21:57
Now it looks that execution is deterministic, but it can introduce breaking change:

 

https://dev.deck.net/47fca1177dc7842e329e31fff48fdd79

 

(compare execution order between 17.0.0 and 16.8.2)

**Comment by geoffreymcgill** [comment] 2018-03-30 22:14
From my testing, the new functionality (17.0) reproduces the native C# expected result.

```
2 ended
1 ended
```

If that's the case (@kosmab please confirm), the old 16.8.2 functionality was defective and is now fixed in 17.0. 

Let us know if you run into a scenario that does not produce the same expected result as C# native.

**Comment by kosmab** [comment] 2018-03-30 22:57
It’s OK.

**Comment by kosmab** [comment] 2018-04-01 18:20
Nice side effect of this change is possibility to wait for task completion with .Result:


 <https://dev.deck.net/4635f9e6f0b325a0a1578a82556f1381> https://dev.deck.net/4635f9e6f0b325a0a1578a82556f1381

 

vs. old

https://deck.net/0b10216b0d6f1e9d7e86c26a9ac2ea5b
