### ISSUE TITLE
InitAttribute(InitPosition.Top) produces empty

### ISSUE THREAD

**Issue by emumanu** [bridgedotnet/Bridge#3506] opened 2018-03-31 21:15 UTC
In a class with only one method, marking that method with [Init(InitPosition.Top)] generates an empty javascript class. I think it shouldn't generate it.

### Steps To Reproduce

https://deck.net/79bf4bfa9d4e861a0fa6ae323f0db533

```csharp
public class Program
{
    [Init(InitPosition.Top)]
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
    }
}
```

### Expected Result

```js
/**
 * @compiler Bridge.NET 16.8.2
 */
var msg = "Hello, World!";

System.Console.WriteLine(msg);
```

### Actual Result

```js
var msg = "Hello, World!";

System.Console.WriteLine(msg);

/**
 * @compiler Bridge.NET 16.8.2
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program");
});
```

**Comment by fabriciomurta** [comment] 2018-10-27 03:34
That's the intended behavior. This is meant to be a means to make startup commands when it is absolutely required to be done before actual Bridge code. If the method therein references to anything within the Demo space, it should be defined.

While this would be nice to have a way to produce clean and simple bridge output, there would also be so much limitation to what can be written in the code, that it will likely kill Bridge purpose at all.

I will mark this as 'wontfix' for now, but we'll be watching the community reaction to this possible feature despite the consequences.

**Closed by fabriciomurta** 2018-10-27 03:34 UTC

**Comment by emumanu** [comment] 2018-10-27 08:02
I was just pointing it out, but It is not a big deal for me.

**Comment by fabriciomurta** [comment] 2018-10-27 17:00
Thanks! Glad to know this is not really being a problem at all.
