### ISSUE TITLE
typeof(string) is transpiled as String, instead of System.String

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2066] opened 2016-11-12 20:46 UTC
http://deck.net/72e3c5bb086a15969beb44058224ea89
```cs
public class Program
{
    public static void Main()
    {
        Console.WriteLine(typeof(object).FullName);
        Console.WriteLine("abc".GetType().FullName);
    }
}
```

**Comment by michaelcheers** [comment] 2016-11-22 13:08
Duplicate of #1293.

**Comment by Porl91** [comment] 2016-12-08 10:46
This is also the case when looking at the 'FullName' property of the Type for String, as shown below:

Actual:
http://deck.net/256af329a7db6d04783a20bf101279fe

Expected:
https://dotnetfiddle.net/qB32TO

**Closed** 2017-02-07 21:34 UTC
Labels: defect
