### ISSUE TITLE
Construct with 2D array breaks build process in certain situations (inline if)

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#122] opened 2015-04-04 03:42 UTC
The following code does not compile:
```
namespace BreakTest
{
    public class Broken
    {
        private static int nx = 4;
        private static int[,] breaker = new int[,]
        { 
            { 1, 2 },
            { 3, 4 }
        };

        private static void BreakIt(int x, int y)
        {
            var retval = (x >= 0 && x < nx && breaker.Length > ((x + 1) * nx)) ? breaker[x, y] : 0;
        }

    }
}
```

Visual Studio displays:
`1>EXEC : error : Parsing error in a file A:\devel\Object.NET\projects\ClassLibrary1\ClassLibrary1\CodeFile1.cs: System.Linq.Enumerable+WhereListIterator'1[ICSharpCode.NRefactory.TypeSystem.Error]`

If debugging:
- Error triggers when calling `ICSharpCode.NRefactory.CSharp.CSharpParser().Parse()`
- The location in bridge is `Bridge.Translator.Translator.GetSyntaxTree()` (Translator.InspectAssembly.cs).
- `Parse()` returns with 'HasErrors' true, and its 'Errors' structure points to the line where the inline `if` is used
- The error actually says that the `?` character in the line is unexpected.

**Comment by vladsch** [comment] 2015-04-04 07:39
I guess It is NRefactory parser bug. For example, if wrap `breaker[x, y]` by braces `()` then all works
Need to check it with latest NRefactory

**Comment by michaelcheers** [comment] 2016-04-18 19:46
@vladsch @fabriciomurta, Seems to work for me: 
[Bridge Live](http://live.bridge.net/#235ef4e51fbf5b6361d607c0d537d014).

**Comment by DaniilVeriga** [comment] 2016-04-26 16:31
Interesting, I could not reproduce it as well.
Tested with the Live Test Case (posted in the previous comment) and also with local VS 2013 and 2015.

**Comment by LeonidVeriga** [comment] 2016-06-05 15:57
This is fixed by NRefactory and Mono.Cecil updates. Added client test and closing the issue.

**Closed by LeonidVeriga** 2016-06-05 15:57 UTC
Labels: defect
