### ISSUE TITLE
"Node is already used in another tree" error when using "using static" (C# 6)

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2535] opened 2017-04-03 14:53 UTC
I can't repro this in a small case on Deck, but we're seeing this when trying to use `using static` in one of our projects. I'll try to gather more info/repro when I get time, but posting it for now in case the report/stack might be useful.

Adding the `using static` doesn't cause issues, but once we try to use it we see this error during compilation. We're using it for one of our own classes, not a built-in one.

```text
Error		Error: Node is already used in another tree.
Parameter name: child    at ICSharpCode.NRefactory.CSharp.AstNode.AddChild[T](T child, Role`1 role)
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.Add(T element)
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.ReplaceWith(IEnumerable`1 nodes)
   at Bridge.Translator.PreconverterFixer.VisitInvocationExpression(InvocationExpression invocationExpression)
   at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitReturnStatement(ReturnStatement returnStatement)
   at ICSharpCode.NRefactory.CSharp.ReturnStatement.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at ICSharpCode.NRefactory.CSharp.MethodDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.NRefactory.CSharp.TypeDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration)
   at ICSharpCode.NRefactory.CSharp.NamespaceDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitSyntaxTree(SyntaxTree unit)
   at ICSharpCode.NRefactory.CSharp.SyntaxTree.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.Translator.Preconvert(MemberResolver resolver)
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()
```

**Comment by DanTup** [comment] 2017-04-10 11:37
Struggling to get a small repro of this... Lots of small unrelated changes seem to cause it to disappear, so it's hard to strip down and keep the project compiling, while removing things code I can't share.

For example, this code causes it (when there are certain other classes/etc.):

```cs
		public override ReactElement Render()
		{

			var a = DOM.Div(
				null,
				Row(null, null, "Name"),
				Row(null, null, "Branding")
			);
			return null;
		}
```

Yet if I just call the `Row` method (the one imported via `using static`) twice like that without it being inside here, it works fine. However, removing other classes caused the above code to work fine too!

If I can get a small enough repro that I can share, I'll post back.

**Comment by geoffreymcgill** [comment] 2017-04-28 07:43
Hi @DanTup – Any luck making a Deck that might reproduce this issue? This looks like something we would want to ensure is functional within 16.x.

**Comment by DanTup** [comment] 2017-04-28 09:01
Unfortunately not - I couldn't even repro locally in a clean project and the weirdest changes seemed to cause the error to go away. I'm out of office till Tuesday now but I'll see if I can get some time to try again next week.

I don't think it's critical (it's compile-time and you can just drop the `using static` and use the type name) so I wouldn't hold up any release for it.

**Comment by geoffreymcgill** [comment] 2017-04-29 01:03
I'm going to close the issue, but if a reproducible case is ever established, we'll gladly reopen.

**Closed by geoffreymcgill** 2017-04-29 01:03 UTC
