### ISSUE TITLE
Method overload failure results in runtime error

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#3327] opened 2017-12-22 12:01 UTC
I have two extension methods that have the same name ("With") but different signatures and Bridge is incorrectly resolving them in some cases.

There are a number of things at play here - generics, interfaces, implicit operators but the overload that is matched is clearly wrong. When I call:

```csharp
.With(_ => _.Error, new AccessDenied());
```

then it should match to this signature:

```csharp
public static T With<T, TPropertyValue>(this T source, Func<T, TPropertyValue> propertyIdentifier, TPropertyValue value)
```

but, instead, it is matching to this one:

```csharp
public static T With<T, TPropertyValue>(this T source, Func<T, TPropertyValue> propertyIdentifier, Func<TPropertyValue, TPropertyValue> valueUpdater)
```

I've included a complete sample below but I've also made it available on Deck (https://deck.net/76802cfecd24329c172bbe8b2d757c15) and on .NET Fiddle (https://dotnetfiddle.net/G2owy0) to confirm that correct behaviour.

```csharp
public class Program
{
    public static void Main()
    {
        // This code results in the following exception being raised:
        //   "Not implemented: With (value updater)"
        // .. which is incorrect because the method overload that should be called is the one that takes
        // a "value" argument and not a "valueUpdater"
        var example = new Example(null).With(_ => _.Error, new AccessDenied());
        
        // If the implicit cast from AccessDenied to Optional<IError> is removed then it resolves correctly
        // and this exception is raised:
        //   "Not implemented: With (direct value set)"
        //var example = new Example(null).With(_ => _.Error, new Optional<IError>(new AccessDenied()));
    }
}

public interface IError
{
	string Message { get; }
}

public sealed class AccessDenied : IError
{
	public string Message { get { return "Access Denied"; } }
}

public sealed class Example : IAmImmutable
{
	public Example(Optional<IError> error)
	{
		Error = error;
	}

	public Optional<IError> Error { get; }
}

public interface IAmImmutable { }

public static class IAmImmutableExtensions
{
	public static T With<T, TPropertyValue>(
        this T source,
        Func<T, TPropertyValue> propertyIdentifier,
        TPropertyValue value) where T : IAmImmutable
	{
		throw new NotImplementedException("Not implemented: With (direct value set)");
	}

	public static T With<T, TPropertyValue>(
        this T source,
        Func<T, TPropertyValue> propertyIdentifier,
        Func<TPropertyValue, TPropertyValue> valueUpdater) where T : IAmImmutable
	{
		throw new NotImplementedException("Not implemented: With (value updater)");
	}
}

public struct Optional<T>
{
	public Optional(T value)
	{
		Value = value;
	}

	public T Value { get; }

	public static implicit operator Optional<T>(T value)
	{
		return new Optional<T>(value);
	}
}
```

**Comment by geoffreymcgill** [comment] 2017-12-22 18:10
Hi @ProductiveRage – Thanks for the excellent defect report and Deck demonstrating how to reproduce. We are investigating this defect and will try to fix right away.

**Comment by vladsch** [comment] 2018-01-03 10:01
Hi,

Can you retest with latest packages (16.6.0)? I cannot reproduces the problem with latest code from dev branch. I guess it is fixed by https://github.com/bridgedotnet/Bridge/issues/3292 which is included to 16.6.0.

**Comment by fabriciomurta** [comment] 2018-01-04 22:00
Deck was just updated to 16.6.0 and I see the same result in the deck and the dotnet fiddle you provided. Can you confirm that works on 16.6.0?

**Comment by fabriciomurta** [comment] 2018-01-09 03:53
Hi! We're moving this to milestone 16.6.0 as it looked as it worked down to that version and closing this. Please let us know if this issue is still reproducible somehow and we'll reopen it.

**Closed by fabriciomurta** 2018-01-09 03:53 UTC
Labels: defect, in progress
