### ISSUE TITLE
Class members emitted as camel-cased in certain circumstances

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#3975] opened 2019-05-28 10:48 UTC
This occurs on Deck.net so Bridge version **17.7.0**. 

I have a type named `User` that when enumerated over, the built output emits JS type definitions with the incorrect casing. Notice that the `User` type has pascal-cased members on the type definition, but when these properties are used in an interpolated string, they become camel / lower-cased.

In this example the casing also corrects if:
- A comment is inserted as line 1.
- The using statements are removed (as they aren't required in Deck.net.)
- The `App` class is removed / renamed.
- String concatenation is used instead of string interpolation.

This may be related to this issue, as it relates to types being named the same as their containing namespace: https://github.com/bridgedotnet/Bridge/issues/3970
If the other issue has been fixed already, would you mind adding this repro as a unit test?

![BridgeCasing](https://user-images.githubusercontent.com/13272784/58471933-f9c57900-813c-11e9-93ec-205b31ac6791.png)

Deck to reproduce:
https://deck.net/99505b1e847dada03c276fe2b440f187

Expected: Pascal-cased members on `User` class usage
Actual: Camel / lower-cased members on `User` class usage

If you need any extra information then just give me a nudge.

**Comment by Porl91** [comment] 2019-05-28 10:49
Also apologies for the noisy screenshot - this was just because when I added comments the issue appeared to vanish.

**Comment by fabriciomurta** [comment] 2019-05-28 16:30
If you remove the `using` lines, it will then work because Bridge internally adds the `using` lines as it sees fit, -and- wrap the whole code in `namespace Demo { }`. So it is the same as fixing the `App.App` issue. But I see the camel casing is still reproducible in Deck with the latest fixes to 17.8.0.

In fact, if you -remove- the `using` lines instead of commenting them out, you'll have the code begin with the `namespace` string which will instruct Deck not to add any using and namespace extras, thus you get unresolve errors.

**Comment by geoffreymcgill** [comment] 2019-05-28 19:49
Thanks for the report. We are investigating.

**Comment by fabriciomurta** [comment] 2019-05-28 20:12
Actually... dev.deck was not really up-to-date when I first tested the issue with it... Just pulled it afresh and.. voila, the issue is fixed! I'd say #3970 fixed it.

Check it out: https://dev.deck.net/99505b1e847dada03c276fe2b440f187

Please let us know if we missed anything in assuming the issue has been fixed with latest 17.8.0 developments!

**Closed by fabriciomurta** 2019-05-28 20:12 UTC

**Comment by geoffreymcgill** [comment] 2019-05-28 20:13
Your original sample is working correctly with the upcoming Bridge 17.8.0 release. 

https://dev.deck.net/99505b1e847dada03c276fe2b440f187

Looks like this has been fixed already.
