### ISSUE TITLE
Can't build using MonoDevelop on Linux

### ISSUE THREAD

**Issue by MangelMaxime** [bridgedotnet/Bridge#860] opened 2016-01-25 21:31 UTC
Hello guys,
I just installed Bridge using nuget packet but I can't build the project. If I use the VSCode project I can build it using the given task.

```

Building: bridge (Debug)

Build started 1/25/2016 10:26:37 PM.
__________________________________________________
Project "/home/shadaen/Projects/herebris/bridge/bridge.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	
	Target CopyFilesMarkedCopyLocal:
		Copying file from '/home/shadaen/Projects/herebris/packages/Bridge.1.10.4/lib/net40/Bridge.dll' to '/home/shadaen/Projects/herebris/bridge/bin/Debug/Bridge.dll'
		Copying file from '/home/shadaen/Projects/herebris/packages/Bridge.1.10.4/lib/net40/Bridge.Html5.dll' to '/home/shadaen/Projects/herebris/bridge/bin/Debug/Bridge.Html5.dll'
		Copying file from '/home/shadaen/Projects/herebris/packages/Bridge.jQuery.2.8.0/lib/net40/Bridge.jQuery2.dll' to '/home/shadaen/Projects/herebris/bridge/bin/Debug/Bridge.jQuery2.dll'
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	
	Target CoreCompile:
		Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/bridge.dll MyClass.cs Properties/AssemblyInfo.cs obj/Debug/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:library /define:DEBUG /nostdlib /reference:/usr/lib/mono/4.5/System.dll /reference:../packages/Bridge.1.10.4/lib/net40/Bridge.dll /reference:../packages/Bridge.1.10.4/lib/net40/Bridge.Html5.dll /reference:../packages/Bridge.jQuery.2.8.0/lib/net40/Bridge.jQuery2.dll /reference:/usr/lib/mono/4.5/mscorlib.dll /warn:4
CSC:  warning CS1685: The predefined type `System.Object' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.ValueType' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Attribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Int32' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.UInt32' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Int64' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.UInt64' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Single' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Double' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Char' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Int16' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Decimal' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Boolean' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.SByte' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Byte' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.UInt16' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.String' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Enum' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Delegate' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.MulticastDelegate' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Array' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Type' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Collections.IEnumerator' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Collections.IEnumerable' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.IDisposable' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.IntPtr' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.UIntPtr' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.RuntimeFieldHandle' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.RuntimeTypeHandle' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Exception' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.ParamArrayAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Runtime.InteropServices.OutAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.ObsoleteAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Runtime.CompilerServices.IndexerNameAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Runtime.InteropServices.GuidAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyCultureAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyVersionAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyFileVersionAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.AttributeUsageAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Diagnostics.DebuggerStepThroughAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Runtime.CompilerServices.ExtensionAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.DefaultMemberAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Runtime.CompilerServices.DecimalConstantAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyProductAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyCompanyAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyCopyrightAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Reflection.AssemblyTrademarkAttribute' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Collections.Generic.IEnumerable' is defined multiple times. Using definition from `Bridge.dll'
		/home/shadaen/Projects/herebris/bridge/../packages/Bridge.1.10.4/lib/net40/Bridge.dll (Location of the symbol related to previous warning)
		/usr/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
CSC:  warning CS1685: The predefined type `System.Collections.Generic.IList' is defined multiple times. Using definition from `Bridge.dll'

---------------------- Done ----------------------

Build: 1 error, 54 warnings
```

```
/usr/lib/mono/4.5/Microsoft.CSharp.targets: Error: Compiler crashed with code: 1. (bridge)
```

My mono version : 

```
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

Do you have any idea ?

**Comment by fabriciomurta** [comment] 2016-01-26 00:07
Hello, on the project settings, check the 'do not reference mscorlib'. This applies to MonoDevelop.

I see you are using a .csproj as parameter of xbuild. You created it on MonoDevelop, right? Then apply the above setting on MonoDevelop, save, and open it with VSCode.

There's a bug in xbuild where it ignores `<NoStdLib />` if it is in an included file. Logged on mono issue tracker but we didn't receive a feedback on how long will it take to be fixed.

If you created with Visual Studio you can also open the project in MonoDevelop, check the setting and save, it will uncheck that box.

If you don't want/can't get into the tool, add a `<NoStdLib>true</NoStdLib>` to your .csproj file.

**Comment by MangelMaxime** [comment] 2016-01-26 21:09
It's seems to remove a lot of errors. But now I get this :

```
/home/shadaen/test/packages/Bridge.1.10.4/build/Bridge.targets: Error: Error: Object reference not set to an instance of an object   at Bridge.Contract.BridgeTypes.InitItems (IEmitter emitter) <0x41ea0ef0 + 0x001ac> in <filename unknown>:0 
  at Bridge.Translator.Emitter..ctor (IDictionary`2 typeDefinitions, Bridge.Contract.BridgeTypes bridgeTypes, System.Collections.Generic.List`1 types, IValidator validator, IMemberResolver resolver, System.Collections.Generic.Dictionary`2 typeInfoDefinitions) <0x41ea0bc0 + 0x0015b> in <filename unknown>:0 
  at Bridge.Translator.Translator.CreateEmitter (IMemberResolver resolver) <0x41ea0b10 + 0x0008b> in <filename unknown>:0 
  at Bridge.Translator.Translator.Translate () <0x41e1dfa0 + 0x003fd> in <filename unknown>:0 
  at Bridge.Build.GenerateScript.Execute () <0x41e1a960 + 0x004cf> in <filename unknown>:0  (test)
```


Here is the code used :

```csharp
using Bridge;
using Bridge.Html5;

namespace test
{
	public class App
	{
		[Ready]
		public static void Main()
		{
			// Simple alert() to confirm it's working
			Window.Alert("Success");
		}
	}
}


```

**Comment by fabriciomurta** [comment] 2016-01-27 00:12
I see you have used `bridge.csproj` as the project name. Right?.. So, is the project name also `Bridge`? If so, this will conflict with Bridge itself. I don't really se anything wrong with your code.

It would be also safe to use a solution name for something different than `Bridge`. Other names to avoid are bridge modules' names, like `Bridge.Html5`, `Bridge.jQuery2`. It would break the code with some namespace conflicts -- although I see in your code sample you avoided using the `Bridge` namespace.

If your answer for these questions is _"No, I am not using Bridge or any Bridge.* name to the solution or project names"_, then just let us know and we'll further investigate what could be causing this for you.

**Comment by MangelMaxime** [comment] 2016-01-27 08:21
Oh sorry, I didn't pay attention to the name sorry. I will try it again.

**Comment by fabriciomurta** [comment] 2016-01-30 01:19
Hello @MangelMaxime, did you get it to work? I was just wondering if we could close this issue.

**Comment by MangelMaxime** [comment] 2016-01-30 13:53
@fabriciomurta Hello, sorry for the late answer didn't tested it yet.

I just try it at the moment and I have the same problem.

Error:
```
/home/shadaen/Projects/herebris/packages/Bridge.1.10.4/build/Bridge.targets: Error: Error: Object reference not set to an instance of an object   at Bridge.Contract.BridgeTypes.InitItems (IEmitter emitter) <0x4162fbf0 + 0x001ac> in <filename unknown>:0 
  at Bridge.Translator.Emitter..ctor (IDictionary`2 typeDefinitions, Bridge.Contract.BridgeTypes bridgeTypes, System.Collections.Generic.List`1 types, IValidator validator, IMemberResolver resolver, System.Collections.Generic.Dictionary`2 typeInfoDefinitions) <0x4162f8c0 + 0x0015b> in <filename unknown>:0 
  at Bridge.Translator.Translator.CreateEmitter (IMemberResolver resolver) <0x4162f810 + 0x0008b> in <filename unknown>:0 
  at Bridge.Translator.Translator.Translate () <0x415ad120 + 0x003fd> in <filename unknown>:0 
  at Bridge.Build.GenerateScript.Execute () <0x415a9c80 + 0x004cf> in <filename unknown>:0  (ClientJS)
```

```c#
using System;
using Bridge.Html5;

namespace ClientJS
{
	public class MyClass
	{
		[Ready]
		public static void Main()
		{
			// Simple alert() to confirm it's working
			Window.Alert("Success");
		}
	}
}
```

Here are the steps I used to create and build the project.

1. I have an existing Solution called : `herebris` with a Project `herebris` inside it.
2. I just add a new Project to the Solution. I named it : ClientJS
3. Place the sample code inside the main class.
4. Change the options inside the project ClientJS to check : `Do not reference mscorlib.dll`

Here is some screens of Xamarin :

![screenshot-3](https://cloud.githubusercontent.com/assets/4760796/12696085/301cf67a-c761-11e5-8a66-2fde7f59bea9.png)

![screenshot-project options - clientjs](https://cloud.githubusercontent.com/assets/4760796/12696086/320f70e8-c761-11e5-9cba-28514ee421ec.png)

**Comment by fabriciomurta** [comment] 2016-01-30 18:52
Alright, I'm sorry.

I have been able to reproduce the problem here and backtrack the last working version of Bridge down to 1.9.0. I.e., if you uninstall bridge package from your project, search for `bridge version:*` and choose the one with version 1.9.0 you'll get your code working. Thank you very much for the report, I will further investigate what has been introduced in 1.10.0 that broke it on Mono!

**Comment by fabriciomurta** [comment] 2016-01-30 22:16
Hello,

I have good and bad news. Good news is that I found the root of the problem, it was introduced on issue #531.

Bad news is that it is a bug in Mono. Its Microsoft.Build.Evaluation.Project() implementation seems to be broken. 

If you make a new Console application on MS Visual Studio (Windows) like this:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Build.Evaluation;

namespace ListCompileFiles
{
    class Program
    {
        static void Main(string[] args)
        {
            var projectFile = "../../ListCompileFiles.csproj";

            var projectInfo = new Project(projectFile);

            Console.WriteLine("'Compile' items list: ");
            foreach (var item in projectInfo.Items)
            {
                if (item.ItemType == "Compile")
                {
                    Console.WriteLine("Compile item: " + item.EvaluatedInclude);
                }
            }

            Console.WriteLine("Listing complete. Total " + projectInfo.Items.Count() + " entries.");

            Console.ReadKey();
        }
    }
}
```

The output you get is:
```
'Compile' items list:
Compile item: Program.cs
Compile item: Properties\AssemblyInfo.cs
Listing complete. Total 29 entries.
```

Now, if you build the exact same program on Linux/MonoDevelop, even though it create a file with `.csproj` extension and the expected `Compile` entries, the output we get is:

```
'Compile' items list:
Listing complete. Total 0 entries.
```

The feature using `Microsoft.Build.Evaluation.Project` is really nice, as it provides a secure way to determine the to-be-compiled files from a project file. But it seems [the class is not implemented like windows version](https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build/Microsoft.Build.Evaluation/Project.cs).

I'm still investigating the issue, as maybe there's a way to address this issue without hurting the other OS.

There may be other errors as well, after this one is solved -- because removing all compilable files from a project in Windows does not lead to an error like it is happening in mono.

**Comment by fabriciomurta** [comment] 2016-01-31 00:00
Alright, I've found a neat solution that works on both Windows and Linux and proposed as an implementation, that will possibly be released with the upcoming Bridge 1.11.

If you want to use bridge right away, you can either manually apply the commit listed above to your github fork and rebuild, or use NuGet package 1.9.0:
`Install_Package Bridge -Version 1.9.0`

Sorry for the delay in getting to the issue, I just wanted to confirm the few questions with you before proceeding to code investigation.

**Comment by MangelMaxime** [comment] 2016-01-31 11:12
Ok @fabriciomurta thanks for your help. I will wait for the 1.11 version of Bridge.

And no problem about the delay, happy to contribute on the project.

**Comment by geoffreymcgill** [comment] 2016-02-01 18:19
Please see https://github.com/mono/mono/pull/2550 for more info regarding the Mono issue.

**Closed** 2016-02-06 14:48 UTC
Labels: defect
