### ISSUE TITLE
C# strings with unicode escapes can be incorrectly translated to minified javascript

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3986] opened 2019-06-03 13:09 UTC
While you have really done an awesome work, fixing all my issues in the 17.8 release, a tiny problem still persists:  
The encoding problem encountered in  #3902  is still present when generating the minified javascript output. There the unicode escapes are again replaced by single characters, which can not be handled by javascript correctly.

**Comment by geoffreymcgill** [comment] 2019-06-04 00:58
Yes, there is an issue. I don't think it's being caused by Bridge, but it's likely the minification tool we're using. We will have to investigate.

**Comment by geoffreymcgill** [comment] 2019-06-06 20:27
A fix for this issue has been created and we will include the fix in the next Bridge release.

**Comment by fabriciomurta** [comment] 2019-06-13 02:40
The fix looks good and should make it to the next release (see assigned milestone).

**Closed by fabriciomurta** 2019-06-13 02:40 UTC
Labels: defect
