### ISSUE TITLE
Failed to resolve assembly: 'Bridge.Html5, Version=1.9.0.0, ...'    at Mono.Cecil.BaseAssemblyResolver.Resolve()

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#511] opened 2015-10-09 04:27 UTC
The following error happens when compiling a project with dependent projects using version 1.9.

"update" all projects to 1.8, restart VS, compile solution => everything is fine.
"update" all projects to 1.9, restart VS, compile solution => this error.
The 1.8=>1.9=>1.8=>1.9 is very repeatable.  I've also verified the .csproj files look good after the version updates.

packages\Bridge.1.9.0\build\Bridge.targets(12,5): error : Error: Failed to resolve assembly: 'Bridge.Html5, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null'    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.TypeReference.Resolve()
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.AddTypeDefs()
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.BuildTypes()
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.MetadataBuilder.BuildModule()
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Bridge.Translator.Translator.InjectResources(Dictionary`2 files)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Bridge.Translator.Translator.SaveTo(String path, String defaultFileName)
packages\Bridge.1.9.0\build\Bridge.targets(12,5): error :    at Bridge.Build.GenerateScript.Execute()

**Comment by fabriciomurta** [comment] 2015-10-09 04:40
VS has some issues with refreshing the libraries. Have you tried unloading and re-loading the individual project thru Visual Studio's solution explorer?

**Comment by fabriciomurta** [comment] 2015-10-09 04:47
By the way, if you do the following:
1. install Bridge 1.8
2. build bridge
3. uninstall bridge 1.8 (or update it to 1.9) without restarting the Visual Studio IDE
4. Try again to build bridge (without completely closing and restarting VS)

You will be running Bridge's Builder for version 1.8 still.

The Bridge's builder will be locked in memory (the first build locks up `Bridge.Builder.dll`). This is a known Visual Studio issue, both VS2013 and VS2015 locks up DLLs loaded in tasks until the running instance is closed. 

You can try this: 
1. Build with bridge
2. Move to the directory where Bridge.Builder.dll is
3. Try to delete the .DLL file. Or replace it with anything else.
4. You will get a 'resource busy' error message.

**Comment by gogglespisano** [comment] 2015-10-09 04:47
I've removed the projects, re-added them, created new projects, tried mixed 1.8 and 1.9 projects.  I've deleted obj, bin, and output folders and restart VS.  I've spent about 10 hours going through combinations and it comes down to the compiling of a project that references other bridge.net projects.

I've built the 1.9 bridge dlls locally and overlaid them on the 1.8 package and updated the .csproj files to say they're 1.9 in the 1.8 folder and it builds fine and has the 1.9 fixes that i need.  The problem is only when the 1.9 compiler is used.

**Comment by gogglespisano** [comment] 2015-10-09 04:49
See my last comment.  I've effectively done what you asked, but the opposite direction.  I've used 1.9 libraries with 1.8 builder and it works.

**Comment by gogglespisano** [comment] 2015-10-09 04:54
For clarification...  it's only the project that references other projects that fails.  The dependent projects build fine with either 1.8 or 1.9.

The dependent projects are another folder level lower off of a common parent, so the path in the .csproj file for the dlls has one more "..\" in the path.  I've wondered if that some how is making the compiler try to use the relative path from the referenced project rather than it's own project.

Is there a way to see more compiler output to find out where it's looking for Bridge.Html5.dll?

**Comment by fabriciomurta** [comment] 2015-10-09 05:01
I couldn't reproduce your issue here. Using VS2013.4 (not latest update).

What I've done:
1. Created a project and added Bridge 1.8.0 (Install-Package Bridge -Version 1.8.0)
2. Built (added some silly code to `Class1.cs` so it just uses Bridge.Html5)
`var x = new BRElement();` to a `Main()` method.
3. Opened NuGet package manager
4. Chosen 'Updates'
5. Updated Bridge
6. Clicked 'Restart now' as VS asked
7. Upon restart, a build went well. 

I could see a difference on output between bridge 1.8 and 1.9. I've defined Main() like this:
```csharp
public void Main(int ijj = 5) {
    var x = new BRElement();
}
```

Which outputs in v1.8:
```javascript
Bridge.define('Bridge.Class1', {
    main: function(i) {
        var x = document.createElement('br');
    }
});
```
And in v1.9:
```javascript
Bridge.define('Bridge.Class1', {
    main: function(i) {
        if (i === void 0) { i = 5; }
        var x = document.createElement('br');
    }
});```

Did I miss some steps here?

**Comment by fabriciomurta** [comment] 2015-10-09 05:03
Okay, I've missed that 'project that reference other projects' detail.

**Comment by gogglespisano** [comment] 2015-10-09 05:03
A single project or individual (unreferenced) projects build fine with 1.8 or 1.9.  The problem only happens on the project that references other projects.

**Comment by fabriciomurta** [comment] 2015-10-09 05:07
I believe the output you want might be in the NuGet package console while you are updating the packages. Try to update them in the console if you're using the dialog.

NuGet package's install.ps1 updates things on the own updated project only, not in its dependencies, and something might be missed, although I am not completely sure on how exactly you setup the project dependency in the solution.

You have a Bridge ClassLibrary project and another, web application on the other project in the same solution? Maybe if you could provide a 'hello world' example of how those projects in the same solution should look like..

**Comment by gogglespisano** [comment] 2015-10-09 05:15
The failing project and the dependent projects are all bridge.net library projects similar to the bridge jquery and bootstrap projects.  The web app is built later.  Also, i'm using VS2015.  I am using the dialog, but i'm updating all 3 projects and i've confirmed the changes by looking in the .csproj files.

I'll try to make an example and see if I can find the trigger, but I've already lost a day on this issue I can't spend too much time on it right now.

**Comment by fabriciomurta** [comment] 2015-10-09 05:50
Okay so, basically you have two ClassLibrary projects, both using Bridge.NET.

First project just uses Bridge, added via NuGet packages.
Second project uses Bridge, added via NuGet packages but also refers to the First project and imports some classes from it.

Is that right? Please update this if you can come up with a sample project structure to reproduce it.

**Comment by gogglespisano** [comment] 2015-10-09 06:42
That's correct except that there are 2 referenced projects.

I haven't come up with a small example that reproduces it yet, but i did try copying the 1.8 BridgeBuilder.dll over my failing 1.9 package and it builds clean, so it's something that the 1.9 compiler doesn't like.

I'm trying to add more and more to the example hoping i'll finally get it to fail.

**Comment by gogglespisano** [comment] 2015-10-09 15:06
Amazingly the problem comes down to a single line using a *const* HTMLColor.  If it doesn't have the const modifier it's ok, Using static is ok.  Plain is ok.

using Bridge.Html5;

namespace BridgeConstColor
{
    public class App
    {
        // const causes the failure
        // static is ok
        // nothing is ok
        public const HTMLColor TheColor = HTMLColor.Blue;

        [Ready]
        public static void Main()
        {
            // Simple alert() to confirm it's working
            Global.Alert( "Success" );
        }
    }
}

**Comment by gogglespisano** [comment] 2015-10-09 15:22
I went back to the 1.9 builder in my large solution and got the error again.  I changed the HTMLColor from const to static and the solution builds and runs fine.

**Comment by fabriciomurta** [comment] 2015-10-09 19:23
Okay, a simple:
```csharp
using Bridge;
using Bridge.Html5;

namespace Bridge19
{
    public class Class1
    {
        public const HTMLColor TheColor = HTMLColor.Blue;
    }
}
```
triggers the error!..

This really looks like an issue we have with Mono.Cecil versus Enum members. So, not really a Bridge issue that we can easily tackle, unfortunately.

There were other situations where we had to replace enum values by static members due to this limitation on the underlying library.

Let's keep this open and look forward for an opportunity either to fix this on Mono.Cecil or have a Mono.Cecil update that addresses this issue.

**Comment by fabriciomurta** [comment] 2015-10-09 19:30
Can you try adding the following to your `bridge.json` file and running with 1.9?

```
injectScriptToAssembly: false
```

[injectScriptToAssembly in documentation](http://bridge.net/kb/global-configuration/#injectScriptToAssembly)

Unfortunately, this option was introduced and set as `true` by default in v1.9.

**Comment by fabriciomurta** [comment] 2015-10-09 20:02
This issue is triggered whenever we declare a `const` variable from an `enum` that comes from a referenced library. This also triggers the error:
`public const System.CaseFirst csf = System.CaseFirst.Lower;`

Left a note on `injectScriptToAssembly` documentation about this.

**Comment by gogglespisano** [comment] 2015-10-09 21:13
I tried the injectScriptToAssembly:false and that worked with const.

It would be nice if the Mono Cecil exception was caught in the bridge builder code so you could add a message to the exception saying the line of code triggering the exception.  That would have made tracking this problem down much easier and quicker.

**Closed** 2015-11-09 13:37 UTC
Labels: question
