### ISSUE TITLE
ToUpper() issue

### ISSUE THREAD

**Issue by daltinkurt** [bridgedotnet/Bridge#3861] opened 2019-02-27 13:21 UTC
When i use `"abc".ToUpper()` it gives an error:
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
```
I used the codes on deck.net helloworld sample:

```csharp
public class Program
{
    public static void Main()
    {
       var msg = "Hello, World!";
       Console.WriteLine(msg.ToUpper());
    }
}
```

**Comment by geoffreymcgill** [comment] 2019-02-27 16:08
Hi @daltinkurt – What browser and OS are you using? I was not able to reproduce the error in Deck.NET. 

https://deck.net/55079c47377b9ae9aada1b917079c971

**Comment by geoffreymcgill** [comment] 2019-03-01 22:23
Closing this issue, but if someone can provide a sample or system setup that demonstrates how to reproduce the issue, then we will re-open and investigate.

**Closed by geoffreymcgill** 2019-03-01 22:23 UTC
