### ISSUE TITLE
Boxed enum types are treated as regular numbers

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2065] opened 2016-11-12 18:44 UTC
### Expected

```
Boat
Boat
Boat
```

### Actual

```
Boat
2
2
```

### Steps To Reproduce

[Deck](http://deck.net/50c6936a439e6c4dcafdb53edfce9dee)

```cs
public enum VehicleType
{
    Car,
    Plane,
    Boat
}

public class Program
{
    public static void Main()
    {
        VehicleType vehicleType = VehicleType.Boat;
        object box = vehicleType;
        
        Console.WriteLine(vehicleType);
        Console.WriteLine(box);
        Console.WriteLine(Enum.Parse(typeof(VehicleType), "Boat"));
    }
}
```

**Comment by michaelcheers** [comment] 2016-11-21 06:57
Related to #1347, #1317, #1312.

**Comment by geoffreymcgill** [comment] 2016-11-22 17:32
Boxing/Unboxing support has been implemented, but moving release to the 16.0 milestone.

**Comment by michaelcheers** [comment] 2016-11-23 13:11
Duplicate of [this comment](https://github.com/bridgedotnet/Bridge/issues/1309#issuecomment-217610825).

**Closed** 2017-02-01 13:53 UTC
Labels: defect
