### ISSUE TITLE
Strange issue with Version ToString

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#510] opened 2015-10-08 10:34 UTC
I can't repro this on live.bridge.net, but it's happening in my local project (which is a build of master, as of about an hour ago).

I'm using some `Version`s in a `string.Format` like this:

```
string.Format("Do you wish to unzip {0}?", file.Version),
string.Format("Unzip {0}", file.Version),
```

But it's coming out as `[Object object]`.

I tried adding an explicit `ToString()` to the end, but it made no difference. The generated JavaScript looks like this:

```
return this.confirm(
    Bridge.String.format("Do you wish to unzip {0}?", file.version),
    Bridge.String.format("Unzip {0}", file.version),
```

![version](https://cloud.githubusercontent.com/assets/1078012/10364058/5ecec382-6db0-11e5-8b44-3010f7e17ce1.png)

**Comment by DanTup** [comment] 2015-10-08 10:36
The output JS looks the same on live.bridge.net, but it works:

```
var s = Bridge.String.format("Hey {0}", new System.Version("constructor$3", 1, 2, 3, 4));
Bridge.global.alert(s);
```

**Comment by LeonidVeriga** [comment] 2015-10-08 15:04
Hi @DanTup! Yes, it is a strange issue. I cannot reproduce it on the latest `master` and `release1.10` branches.

The source code:
```C#
using Bridge;
using Bridge.Html5;
using System;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            var s1 = string.Format("Hey {0}", new System.Version(1, 2, 3, 4));
            Console.Log(s1);

            var s2 = string.Format("Hey {0}", (new System.Version(1, 2, 3, 4)).ToString());
            Console.Log(s2);
        }
    }
}
```

Generated JavaScript:
```JavaScript
var s1 = Bridge.String.format("Hey1 {0}", new System.Version("constructor$3", 1, 2, 3, 4));
console.log(s1);

var s2 = Bridge.String.format("Hey2 {0}", (new System.Version("constructor$3", 1, 2, 3, 4)).toString());
console.log(s2);
```

Console output (Chrome, FF, IE):
  Hey1 1.2.3.4
  Hey2 1.2.3.4

Can you please check if the exact soure code above (as a separate simpe project) works the same in your environment.

**Comment by DanTup** [comment] 2015-10-15 13:19
This seems to be related to JSON parsing (my data was coming from a server when I hit the issue, but when trying to repro, it was not).

[live example here](http://live.bridge.net/#e504960a3934f1d7f67c)

        // Works as expected
        var v1 = new Version(1, 2, 3, 4);
        var v2 = JSON.Parse<Version>(JSON.Stringify(v1));
        Global.Alert(v2.ToString());
        
        // Alerts "[Object object]"
        var d1 = new Danny { Version = new Version(1, 2, 3, 4) };
        var d2 = JSON.Parse<Danny>(JSON.Stringify(d1));
        Global.Alert(d2.ToString());

Would you expect this to work? (I'm not sure if JSON.Parse is able to handle this?).

If you doexpect this to work, I also noticed the JSON that comes out of JSON.Stringify is different to what I get back out of ASPNET (yours is prefixed with underscores for each property, and uppercase, like `_Build` but I get `build` from my server). Ideally, the formats would match, so these instances can be carried back and forth between client/server (though I appreciate this is more like a feature request than a bug).

**Comment by DaniilVeriga** [comment] 2015-11-02 16:03
As for `JSON.Parse<T>(...)` it is going to work with primitives only. Here is a related issue - #98. Unfortunately, it doesn't work for custom types, because it requires Reflection support which is not presented in Bridge v1. So, slated to v2.

**Comment by DaniilVeriga** [comment] 2015-11-10 13:11
So, it looks like all is okay with System.Version (just tested a little to ensure) and the issue is with `JSON.Parse<T>(...)` that there is a dedicated issue for. I am closing the current issue if you don't mind.

**Closed by DaniilVeriga** 2015-11-10 13:11 UTC
Labels: invalid

**Comment by DanTup** [comment] 2015-11-11 17:21
Yep, that's fine by me.
