### ISSUE TITLE
Move System.String.LocaleCompare Methods to Bridge.Html5

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2397] opened 2017-02-16 04:43 UTC
Method **System.String.LocaleCompare** is not a part of C# API and should be moved into **Bridge.HTML5** within the JavaScript **String** api.

**Comment by LeonidVeriga** [comment] 2017-02-16 17:00
Duplicate of #2392

**Closed** 2017-02-16 17:01 UTC
Labels: duplicate
