### ISSUE TITLE
SortedList<T> does not allow this[TKey]{set} for a key not present in the dictionary.

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [bridgedotnet/Bridge#3828] opened 2019-01-20 15:10 UTC
Hi.

I've noticed that SortedList.Add(...) works with a key that is not present in the dictionary, while SortedList[key]=value does not.

According to MS doc:
"If the specified key is not found, a get operation throws a KeyNotFoundException and a set operation creates a new element using the specified key."

This would be nice to have both classes behaving the same... :)

Regards,
Sylvain.

**Comment by geoffreymcgill** [comment] 2019-01-20 21:53
HI @SylvainDebaudringhien – Thanks for the report. We will investigate and try to improve with the next release.

**Comment by SylvainDebaudringhien** [comment] 2019-01-21 08:57
Thanks!

I think (not sure though) that the current implementation starts an endless loop...
Sylvain.

**Comment by ProductiveRage** [comment] 2019-01-21 16:13
I think that this and issue #3827  might both be caused by the generic sorted list class have two indexer properties and the compiler not handling that correctly (https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Collections/Generic/SortedList.cs).

**Comment by samuelGrahame** [comment] 2019-02-12 20:22
I think this is to do with the support of js objects - a["test"] will work without an indexer.

so if you used string as the key the js version is being used.

you could fix this by using templates attributes to write the js aka set/get item

**Comment by geoffreymcgill** [comment] 2019-02-25 20:39
This issue has been fixed and the fix will be included in the upcoming Bridge 17.7.0 release.

**Comment by SylvainDebaudringhien** [comment] 2019-02-26 08:49
Many thanks! :)

**Comment by geoffreymcgill** [comment] 2019-02-26 09:27
We will just leave this issue open until the PR is fully tested and merged into the master branch.

**Comment by fabriciomurta** [comment] 2019-03-08 05:21
Fixed and merged upstream, it will be available next release (I'd rather mention the issue milestone as a general rule of thumb, as there's always chances the version number I say here would change prior the actual release -- and the milestone is guaranteed in sync).

**Closed by fabriciomurta** 2019-03-08 05:21 UTC
Labels: defect, in-progress
