### ISSUE TITLE
Loss of actual type while 'boxing'

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#2516] opened 2017-03-29 20:28 UTC
### Steps To Reproduce

https://deck.net/5b2828f9e4d30ae204e828a585237ad6

```c#
public class Program
{
    public static void Main()
    {
        double someDouble = 2.0;
        SomeFunc(someDouble);
    }
    
    static void SomeFunc(object someDouble){
        Console.WriteLine(someDouble.GetType().FullName);
    }
}
```

### Expected Result

```js
System.Double
```

### Actual Result

```js
System.Int32
```

**Comment by LeonidVeriga** [comment] 2017-03-29 20:32
Thanks for submitting this report and for providing the simplified sample demonstrating how to reproduce.

The issue is fixed in current **master** branch. We will ensure our tests cover your scenario and add a test if required to avoid any regression issues in future.

**Comment by danieldegtyarev** [comment] 2017-03-29 20:34
Wow, thank you! This is a blocker for me right now, so I happy to hear that!

**Comment by LeonidVeriga** [comment] 2017-03-30 19:52
The issue has been fixed and covered by the tests of:
- #2077 Support boxing/unboxing operations
- #1347 Base types give incorrect type names

**Closed by LeonidVeriga** 2017-03-30 19:52 UTC
Labels: defect
