### ISSUE TITLE
No exception in console if async entry point is used

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3650] opened 2018-06-25 01:48 UTC
It looks like jquery call implemented as async method (using TaskCompletionSource and done/fail callbacks) have the same problem.

I cannot provide sample for Bridge.jQuery2 because it will be to much listing.  
Though I hope that Main entry has such problems for the same reason.  

Solving of this issue for jQuery callbacks (as well as for Main entry point) is very crucial for me to debug my app.

### Steps To Reproduce

https://deck.net/ed1f1224807f979c34e36508fd9bf3a0

```csharp
public class Program
{
    public static async Task Main()
    {
        Console.WriteLine("main");

        throw new InvalidOperationException("test!");
    }
}
```

### Expected Result

```
main
uncaught exception: System.InvalidOperationException: test!
```

### Actual Result

```js
main
```

**Comment by fabriciomurta** [comment] 2018-07-04 05:18
Hello, @hardhub! Thanks for the report! We have fixed and merged the changes to fix the issue upstream to our `dev` branch. But I'm not sure this will tackle the issue you are having with the Bridge.jQuery2 framework support package.
Actually, if the issue is inherent to one of the frameworks, the issue should (ideally) be logged under the frameworks repo bridgedotnet/Frameworks.

Anyway, I'm not 100% sure I would be alright to mark the issue as fixed now -- the deck you provided definitely works, and that's all base we have to identify and fix the issue.

So, as per the reproducible report and pull request, the issue _should_ be fixed. If it's still reproducible with Bridge.jQuery and you come up with a code sample for us to reproduce it, then please log the issue in bridgedotnet/Frameworks repo -- unless you have reasons to believe the issue pertains to Bridge's core, of course. Is that reasonable for you? (closing for now, but we're open for your feedback)

**Closed by fabriciomurta** 2018-07-04 05:18 UTC
Labels: defect, in-progress, premium
