### ISSUE TITLE
Regression in default parameters in 17.8.0

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#4003] opened 2019-06-13 10:55 UTC
Default parameters in methods do not work.

### Steps To Reproduce

https://deck.net/093cb347474cc0cfa7a1d72aa856a932

```csharp
[Flags]
public enum SomeEnum
{
    A = 1 << 0,
    B = 1 << 1
}

public static class SomeClass
{
    public static async Task<int> Method(SomeEnum some = SomeEnum.A)
    {
	return await Task.FromResult(123);
    }
}

public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
        
        // Try other C# Samples from
        // the Button in the top right.
    }
}
```

### Expected Result

```js
normal code
```

### Actual Result

```js
exception
```

**Comment by geoffreymcgill** [comment] 2019-06-13 17:53
Duplicate of #3994

**Closed by geoffreymcgill** 2019-06-13 17:53 UTC
Labels: duplicate
