### ISSUE TITLE
Move non-standard System.String.Replace Method overloads to Bridge.Html5

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2398] opened 2017-02-16 06:06 UTC
The following **System.String.Replace** overloads are not a part of C# API and should be moved into **Bridge.HTML5** within the JavaScript **String** api.

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/String.cs#L491-L525

```c#
public extern string Replace(string substr, Delegate callback);
public extern string Replace(string substr, Func<string, string> callback);
public extern string Replace(string substr, Func<string, int, string> callback);
public extern string Replace(string substr, Func<string, int, string, string> callback);
```

**Comment by LeonidVeriga** [comment] 2017-02-16 16:29
Duplicate of #2392

**Closed by LeonidVeriga** 2017-02-16 16:29 UTC
Labels: duplicate
