### ISSUE TITLE
Activator.CreateInstance enum creation

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1909] opened 2016-10-01 11:07 UTC
### Expected

```js
// should return default enum value (0)
Activator.CreateInstance(typeof(EnumType)) 
```

### Actual

```
// returns false (and cannot be casted to EnumType)
jsActivator.CreateInstance(typeof(EnumType)) is EnumType
```

**Comment by geoffreymcgill** [comment] 2016-10-01 18:53
Hi @yuvaltz - Thanks for submitting this defect. We will investigate and try to fix right away.

I have a favour to ask... can you link to a [Deck.NET](http://deck.net/) sample demonstrating exactly how to reproduce these problems? This would certainly help us focus on the problem and speed up investigation.

**Comment by yuvaltz** [comment] 2016-10-01 19:17
Sure, no problem

**Comment by LeonidVeriga** [comment] 2016-10-07 10:27
Duplicate of #1595

**Closed** 2016-10-07 10:34 UTC
Labels: defect
