### ISSUE TITLE
GetType() returns wrong type due to lack of proper boxing

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2055] opened 2016-11-11 15:29 UTC
### Expected

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        $main: function () {
            var i = 0;
            var f = 0.0;

            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Int32));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Single));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Int32));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Single));

            var oi = SomeMagicBoxingTrickOlalala(i, System.Int32);
            var of = SomeMagicBoxingTrickOlalala(f, System.Single);

            Bridge.Console.log(Bridge.Reflection.getTypeFullName(Bridge.getType(oi)));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(Bridge.getType(of)));
        }
    });
});
```

```
System.Int32
System.Single
System.Int32
System.Single
System.Int32
System.Single
```

### Actual

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        $main: function () {
            var i = 0;
            var f = 0.0;

            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Int32));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Single));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Int32));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(System.Single));

            var oi = i;
            var of = f;

            Bridge.Console.log(Bridge.Reflection.getTypeFullName(Bridge.getType(oi)));
            Bridge.Console.log(Bridge.Reflection.getTypeFullName(Bridge.getType(of))); //System.Int32 - WRONG
        }
    });
});
```

```
System.Int32
System.Single
System.Int32
System.Single
System.Int32
System.Int32
```

### Steps To Reproduce

[Deck](http://deck.net/690c6a3cb1929e3cc16244417e983bc9)

```cs
public class Program
{
    public static void Main()
    {
        int i = 0;
        float f = 0.0f;

        Console.WriteLine(typeof(int).FullName); 
        Console.WriteLine(typeof(float).FullName); 
        Console.WriteLine(i.GetType().FullName); 
        Console.WriteLine(f.GetType().FullName); 

        object oi = i;
        object of = f;

        Console.WriteLine(oi.GetType().FullName); 
        Console.WriteLine(of.GetType().FullName); 
    }
}
```

**Comment by michaelcheers** [comment] 2017-01-16 13:53
Duplicate of #1347.

**Closed** 2017-02-01 13:53 UTC
Labels: defect
