### ISSUE TITLE
Bridge.getType for number types (e.g. int, long)

### ISSUE THREAD

**Issue by sluu99** [bridgedotnet/Bridge#1184] opened 2016-04-13 06:06 UTC
Hi all! Thank you for all the hard work on this super cool project!
I understand this is somewhat a compatibility issue 'cause JavaScript only has a `Number` type. Though I wonder if there are any plans or idea suggestions to support this scenario?

### Expected
True

### Actual
False

### Steps To Reproduce

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        int x = 1;
        Console.WriteLine(x.GetType() == typeof(int));
    }
}
```

**Comment by geoffreymcgill** [comment] 2016-04-13 06:22
Hi @sluu99. Very interesting question. 

We will discuss this scenario and get back to you.

I made a simple live sample to test with:
http://live.bridge.net/#afa4a56c0ff6325bfe23898be76a2ca1

**Comment by geoffreymcgill** [comment] 2016-04-14 12:33
Hi @sluu99,

We discussed this issue and figured out what was going wrong. 

We came up with a plan to fix. The fix has not been implemented yet, but we're gong to try and get this done right away. I feel this is a pretty serious defect, so I'd like to see it fixed asap.

Once the fix has been implemented, the following scenario should return the correct expected results. 

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        int x = 1;
        Console.WriteLine(x.GetType());
        Console.WriteLine(x.GetType() == typeof(int));
        
        var person = new Person();
        Console.WriteLine(person.GetType() == typeof(Person));
    }
}

public class Person{}```

Thanks for bringing this issue to our attention, and for providing the concise code sample demonstrating how to reproduce the issue.

**Closed** 2016-04-15 19:59 UTC
Labels: defect, in progress

**Comment by geoffreymcgill** [comment] 2016-04-16 02:06
Looks like Bridge 1.12.1 is working well now. Public release should be Monday or Tuesday of the coming week. 

You can test with latest *master* branch. 

Recompile in *Release* mode and a new .nupkg added to */bin/Release* folder.

**Comment by geoffreymcgill** [comment] 2016-04-16 02:09
We also added support for the `.GetType().FullName` property.

**Example**

```csharp
using Bridge.Html5;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            int x = 1;
            Console.WriteLine(x.GetType().FullName);
            Console.WriteLine(x.GetType() == typeof(int));

            var person = new Person();
            Console.WriteLine(person.GetType().FullName);
            Console.WriteLine(person.GetType() == typeof(Person));
        }
    }

    public class Person { }
}
```

Writes the following to the Console:

```Bridge.Int32
true
Demo.Person
true```

**Comment by sluu99** [comment] 2016-04-16 06:25
Wow! Really impressed with the quick turn around. I looked through the change set to understand the fix a little, please correct me if I'm wrong (I have not had a chance tried out the fix yet). 
From the looks of it, we are only differentiation between integers (Int32) and real numbers (Double)? So what does it mean for `long` (Int64) and `float` (Single)?

**Comment by geoffreymcgill** [comment] 2016-04-26 06:29
Hi @sluu99,

At the moment, there may be differences between the native C# compiler experience and Bridge. A **long** type check will return the correct result when compiled to JavaScript, although a **float** will return as **int**. 

At the moment, only creating matching custom types on the client to mirror the C# native types would solve this issue, although that would mean wrapping object that are currently handled as native types in custom objects. There would certainly be a serious performance hit.

We haven't forgotten about this thread, but there's just not a great answer, at least at the moment. We will continue to think about the problem and try to come up with an acceptable solution.

**Comment by DaniilVeriga** [comment] 2016-04-26 15:16
A similar/same problem has been reported in #1248.

**Comment by geoffreymcgill** [comment] 2016-05-05 06:42
Related to #1248, #1292, #1293 and #1294.

**Comment by calcock** [comment] 2016-10-12 01:22
Hi friend! 

Have you  ever seen something like that? That is something really new and awesome, more information here <http://believe.mnkites.com/lnptu>


Faithfully, calcock
