### ISSUE TITLE
Incorrect delegate creation of generic methods

### ISSUE THREAD

**Issue by Dia6lo** [bridgedotnet/Bridge#1722] opened 2016-08-30 11:03 UTC
### Expected
No error, `0` in console.

### Actual
`Uncaught TypeError: T is not a constructor`

### Steps To Reproduce
Sample ([Bridge Deck](http://deck.net/9395474cbfadc342a49577695797a9b3)):
```cs
public class Program
{
    public static void Main()
    {
        var foo = new Action(Foo<int>);
        foo();
    }

    private static void Foo<T>() where T: new()
    {
        Console.WriteLine(new T().ToString());
    }
}
```

### Steps To Workaround
Use lambdas instead of method groups:
```csharp
var foo = new Action(() => Foo<int>());
```
instead of
```csharp
var foo = new Action(Foo<int>);
```

**Comment by vladsch** [comment] 2016-09-04 14:06
The issue is not reproduciable with latest code

**Comment by Dia6lo** [comment] 2016-09-04 14:39
That's strange. Here is solution in which I can reproduce it:
https://github.com/Dia6lo/Bridge_1722

**Comment by vladsch** [comment] 2016-09-04 15:39
Your solution uses Bridge 1.14, I meant that the issue is not reproduciable with latest code (from git repository)

**Comment by LeonidVeriga** [comment] 2016-09-04 21:30
We will add a test case into our Client tests and then close the issue.

**Comment by LeonidVeriga** [comment] 2016-09-09 11:33
A client test added to ensure the issue will not re-appear again.

**Closed by LeonidVeriga** 2016-09-09 11:33 UTC
Labels: defect
