### ISSUE TITLE
Null reference error in Bridge.Translator.Emitter.GetInline(IEntity)

### ISSUE THREAD

**Issue by pnjeffries** [bridgedotnet/Bridge#3387] opened 2018-01-28 11:57 UTC
I'm attempting to compile an existing C# library with Bridge.Net, however building fails with the following error message:

Error		2018-01-28T01:09:32:356 	Error		Object reference not set to an instance of an object.    at Bridge.Translator.Emitter.GetInline(IEntity entity)
   at Bridge.Translator.MetadataUtils.ConstructMemberInfo(IMember m, IEmitter emitter, Boolean includeDeclaringType, Boolean isGenericSpecialization, SyntaxTree tree)
   at Bridge.Translator.MetadataUtils.<>c__DisplayClass0_0.<ConstructTypeMetadata>b__2(IMember m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Bridge.Translator.MetadataUtils.ConstructTypeMetadata(ITypeDefinition type, IEmitter emitter, Boolean ifHasAttribute, SyntaxTree tree)
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.BridgeCompilerTask.Execute()	Nucleus.JS	C:\Users\jeffe\OneDrive\Documents\Nucleus\Nucleus\Nucleus.JS\..\Nucleus\Model\Loading\PanelLoad.cs	12	

(The error is shown to occur in the PanelLoad class, with source here: https://github.com/pnjeffries/Nucleus/blob/BridgeDotNet_Compile_Bug/Nucleus/Nucleus/Model/Loading/PanelLoad.cs - however there is nothing particularly special about this class definition to indicate cause.)

### Steps To Reproduce

- Download library source code here: https://github.com/pnjeffries/Nucleus/tree/BridgeDotNet_Compile_Bug
- Build the Nucleus.JS sub-project.
- Build should fail with the above error message.

**Comment by geoffreymcgill** [comment] 2018-03-11 10:38
Hi @pnjeffries – Still having compilation problems? Any chance you could isolate a sample that demonstrates how to reproduce this issue? Ideally a [Deck](https://deck.net).

**Comment by geoffreymcgill** [comment] 2018-03-11 13:45
Hi @pnjeffries – Please update to the latest public release (16.8.2) of Bridge. We think this issue might have been related to something fix after the 16.7.0 release that you're using in the project.

Hope this helps.

**Comment by geoffreymcgill** [comment] 2018-03-11 13:52
We were able to compile the Nucleus.JS project using Bridge 16.8.

**Comment by fabriciomurta** [comment] 2018-10-27 04:12
I'm marking this as "invalid" and closing as we were unable to reproduce it, and also didn't get feedback from @pnjeffries for a long while.

**Closed by fabriciomurta** 2018-10-27 04:12 UTC
