### ISSUE TITLE
[Core] FileName does not work for interfaces when outputBy is 'Class'

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#242] opened 2015-05-05 21:03 UTC
```C#
using Bridge;
using Bridge.Html5;

namespace Demo
{
    public class App
    {
        [FileName("demo.js")]
        interface ISimple
        {
        }

        class A : ISimple
        {
        }

        [Ready]
        public static void Main()
        {
            ISimple a = new A();
        }
    }
}
```

In **bridge.json** set the output option by Class: `"outputBy": "Class"`

Actual result: `ISimple` interface is generated into **app.iSimple.js**
Expected result: `ISimple` interface is generated into **demo.js** according to `[FileName("demo.js")]`

**Comment by fabriciomurta** [comment] 2015-05-05 22:24
I think this is duplicate of #77

**Comment by fabriciomurta** [comment] 2015-05-06 16:46
Talked to @LeonidVeriga about the duplicate, closing this to resolve on #77.

**Closed by fabriciomurta** 2015-05-06 16:46 UTC
Labels: vNext
