### ISSUE TITLE
Memory leaks in Bridge.fn.bind() with some kinds of callbacks

### ISSUE THREAD

**Issue by andersnm** [bridgedotnet/Bridge#2212] opened 2017-01-02 14:11 UTC
### Expected

```
Bridge-generated app.$$bind array should have less than 1000 elements
```

### Actual

```
Bridge-generated app.$$bind array has more than 1000 elements
```

### Steps To Reproduce

[Deck](http://deck.net/619f7ee5f42f5396afcae1c6c6715e07)

This is a reduced version of Bridge.React's AppDispatcher from @ProductiveRage (a Flux implementation). The issue is only triggered if the callback touches both a local variable AND a class member variable (which seems to affect whether and how fn.bind() is called). There are no leaks if removing the access to either local OR member variables.
 

```cs
using Bridge;
using System;

namespace BridgeLeakTests {

    public sealed class DispatcherMessage {
        public DispatcherMessage(IDispatcherAction action) {
            Action = action;
        }

        public IDispatcherAction Action { get; private set; }

        public void Do<T>(Action<T> work) where T : class, IDispatcherAction {
            work(Action as T);
        }
    }

    public interface IDispatcherAction { }

    public sealed class AppDispatcher {
        private event Action<DispatcherMessage> _dispatcher;

        public void Register(Action<DispatcherMessage> callback) {
            _dispatcher += callback;
        }

        public void Dispatch(IDispatcherAction action) {
            _dispatcher(new DispatcherMessage(action));
        }
    }

    class MyAction : IDispatcherAction { }

    public class App {
        int member = 7;

        public App() {

            var dispatcher = new AppDispatcher();

            var state = 99;

            dispatcher.Register(message => {
                message.Do<MyAction>(action => {
                    // Comment out either of the following lines to prevent leaks:
                    member += 1;
                    state += 1;
                });
            });

            for (var i = 0; i < 1000; i++) {
                dispatcher.Dispatch(new MyAction());
            }
        }

        public static void Main() {

            var app = new App();

            var len = Script.Write<int>("app.$$bind.length");
            // .$$bind.length should not be > 1000, leaking a closure for each event invocation
            Console.WriteLine(len);
        }
    }
}
```

**Comment by geoffreymcgill** [comment] 2017-01-02 14:22
Hello @andersnm, 

Welcome to Bridge.NET!

Thanks for reporting this issue and providing the simplified sample demonstrating how to reproduce. We will investigate.

**Comment by vladsch** [comment] 2017-01-02 15:24
Hi
I don't think that it is a memory leaking. Let me explain. `Bridge.fn.bind` always stores bound function in the object which was a scope (in `$$bind` property). It is required to support such cases
http://deck.net/9da2d3ccb7e983128b33402506ef7203
When `scope` object will be released then bound functions will be releases also

In your sample, there bound function which is passed to `dispatcher.Register` and inside that finction there is another bound function which is passed to `message.Do<MyAction>`
First bound function is invoked 1000 times, so `message.Do<MyAction>` is invoked 1000 times also (in other words, `Bridge.fn.bind` is invoked 1000 times). We have 1 and 1000  `Bridge.fn.bind` invocations. 
There is local variable usage inside inner lambda therefore we cannot transform that lambda to named function to avoid new function creation. So, new function is created and new bound function is created each time when you invoke `Dispatch`. If reove `state` usage then Bridge can save lambda in to the named function which is used each time when Dispatch is invoked 

So, in my opinion it is not bug, it is expected behaviour. May be it is possible little optimization, if we try to make bound version of function create expression (`function(){}`) then saving orginal function is not required because reference to that expression is not accessable in other part of code

Sorry if my explanation is not very clear

**Comment by andersnm** [comment] 2017-01-02 17:10
Thanks for the quick response and explanation @vladsch . Now I understand what's going on and why, and should be able to fix these leaks in our code. 

If anything could be done in Bridge that'd be nice too, although it sounds like there is a tricky difference between .NET delegates and JS function objects

**Comment by ProductiveRage** [comment] 2017-01-03 16:18
If I understand what's going on here, if the $$bind scope is recorded against a long-lived reference then it _could_ act like a memory leak in that memory usage would increase over time while the application is running? If the "App" class instance existed for the lifetime of the (if it was static, for example) and if it was dispatching items regularly while the application was alive?

I'm a bit unclear what the $$bind array is used for. I looked through the Bridge JavaScript (from [Deck.NET's bridge.js](http://deck.net/resources/js/bridge/bridge.js) - since I was looking at Vlad's example) and it seems like $$bind only ever gets created and added to, I couldn't actually see the code that looked for values in it when comparing functions. If $$bind is only used for comparing functions (that may or may not have been passed through Brige.fn.bind), wouldn't it be possible to make Bridge.equals more aware of how bound functions are represented?

```
public class Program
{
    public void M() { }
    
    public static void Main()
    {
        var app = new Program();
        Action m1 = app.M;
        Action m2 = app.M;
        
        Console.WriteLine("Using Bridge.staticEquals/equals: " + (m1 == m2));
        Console.WriteLine("Using DoDelegatesMatch: " + DoDelegatesMatch(m1, m2));
    }
    
    // This sort of logic could be incorporated into Bridge.equals rather than relying upon $$bind
    private static bool DoDelegatesMatch(Delegate x, Delegate y)
    {
        /*@
        if (!x && !y) {
        	return true;
        }
        else if (!x || !y) {
        	return false;
        }
        if (!x.$method || !x.$scope) {
        	return x === y;
        }
        return (x.$method === y.$method) && (x.$scope === y.$scope);
        */
        return false;
    }
}
```

(Also available at Deck.NET at [http://deck.net/61040c9e2e9b50fe92b9e3adb106b2ca](http://deck.net/61040c9e2e9b50fe92b9e3adb106b2ca)).

**Comment by andersnm** [comment] 2017-01-03 16:39
For reference, simplified the original example further:

```cs
class App {
	int test = 0;

	void Run() {
		var mytest = 1;
		Func<Action> a = () => {
			Action b = () => {
				test = mytest;
			};
			return b;
		};

		for (var i = 0; i < 1000; i++) {
			a()();
		}
	}

	static void Main() {
		var app = new App();
		app.Run();
		Script.Write("console.log(app.$$bind.length);");
	}
}
```
http://deck.net/203b45d06765b8269a0c281e42b88cce

**Comment by andersnm** [comment] 2017-01-04 11:15
I hoped the workaround was not too intrusive: rewrite all C# arrow functions to use only 1) member variables from the calling class, and/or 2) local variables and arguments defined in the innermost function. However after more testing this is IMHO not a viable solution. The end result is having to write a kind of warped C# to accommodate for implementation details of the Bridge compiler.

@ProductiveRage's suggestion to expand Bridge's equals() to replace $$bind sounds promising, but I'm not familiar enough to comment on it. 

Here's another example showing three problematic variables: dispatcher, api and pageIndex. All closures leak to $$bind when processing the DataListRefreshClicked action. We could move dispatcher and api as members of the store, but wouldn't really work for the pageIndex (f.ex during multiple concurrent requests). Although there are ways to work around the pageIndex too, it potentially affects unrelated components (e.g change the server side to include pageIndex in its response).

```cs
public class DataStore {
	public event Action Change;
	public DataState State;

	public DataStore(AppDispatcher dispatcher, DataApi api) {
		State = new DataState(... );

		dispatcher.Register(message =>
			message
				.If<DataListRefreshClicked>(action =>
					// Make an AJAX request with pageIndex parameter
					GetDatas(dispatcher, api, State.DataList.SelectedPageIndex)
				).Else<DataListUpdated>(action =>
					State = State.With(_ => _.DataList, action.DataList)
				).IfAnyMatched(OnChange);
		));
	}
	
	private void GetDatas(AppDispatcher dispatcher, DataApi api, int pageIndex) {
		api.GetDatas(
			pageIndex, 
			response => 
				dispatcher.HandleViewAction(
					// Want to return pageIndex, but referencing it causes the lambda to leak
					new DataListUpdated(ParseDataResponse(response, pageIndex))
				)
		);
	}
}
```

**Comment by vladsch** [comment] 2017-01-04 12:04
I guess that changing equals functions is quite interesting, we will remove those $$bind cache object in next release

**Comment by ProductiveRage** [comment] 2017-01-04 13:07
I would be happy to look into it and submit a pull request but it's the sort of thing that would definitely want unit tests - is it possible to get hold of the NuGet packages for the beta Bridge.Test.Core package (so that I can build the full Bridge.Dev solution) or is it still not quite ready for public consumption?

**Comment by vladsch** [comment] 2017-01-10 17:06
Additional note, equals already check bound functions. The reasons why we add cache is the following issue
https://github.com/bridgedotnet/Bridge/issues/1721

So, cache is required. At this moment, i see the single optimization only - do not cache function expression (only named functions)

**Comment by ProductiveRage** [comment] 2017-01-11 17:20
Ahhhh, yes, that's nasty.

So if there a named C# method then you need to cache it so that it can be "reused" when passed to a remove-listener method. But an inline function expression does not need to be cached because it's not possible to reuse that function because it's not stored anywhere.

I guess there's one slight variation on this case, which is if you have a function expression recorded in a named variable - eg.

`Func<string> doSomething = () => "Dan";`

That would need to be treated the same as the name method approach (and be cached).

Issue #1721 mentions that it doesn't happen with static methods, which makes sense because they don't have to be bound to anything.

**Closed** 2017-01-12 18:24 UTC
Labels: defect

**Comment by vladsch** [comment] 2017-01-23 19:10
I guess that Bridge can use WeakMap (if browser supports it), it is like weak references in .NET
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

**Comment by samuelGrahame** [comment] 2017-01-24 22:41
I think there might be a different solution, Have the ability to turn on anonymous namespace, 

For instance, Put all the no named call backs in there.

![image](https://cloud.githubusercontent.com/assets/13449963/22270070/243f899c-e2e2-11e6-9737-49883df9d2c4.png)

As this is how microsoft handles it anyway.

As my Grid Control I made runs off the scroll event - i had millions of unbinded click events to my cells - I had to name them all
