### ISSUE TITLE
Implement generic EventHandler<T> class 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#328] opened 2015-07-24 05:57 UTC
http://forums.bridge.net/forum/community/help/326-system-eventargs?p=338#post338

**Comment by fabriciomurta** [comment] 2015-07-24 18:17
Duplicate of #326.

**Comment by geoffreymcgill** [comment] 2015-07-24 18:36
Similar to #326. Just add the generic <T> member too.

**Comment by fabriciomurta** [comment] 2015-07-27 06:45
Yes, my mistake. Was trying to keep one issue per forum thread but they are really different things I overlooked while reviewing this.

**Comment by fabriciomurta** [comment] 2015-07-27 07:20
Pushed the fix in branch `328-eventHandlerSupport`. Will merge its implementation is what we need.

**Closed** 2015-07-29 04:48 UTC
Labels: feature, in progress
