### ISSUE TITLE
[Init] deck from wiki not working in visual studio build.

### ISSUE THREAD

**Issue by JonnyS7G** [bridgedotnet/Bridge#3829] opened 2019-01-25 04:37 UTC
This may be a general javascript issue and not a Bridge specific issue. But the Init attribute is not working for me. I am a web development noob so I may be missing something obvious. My javascript file is identical to the javascript in the deck, but it is giving an error.

### Steps To Reproduce
1. Create new Bridge class library named InitTest in VS 2017 (with Bridge nuget version 17.6.0)
2. Copy & Paste code from deck into App.cs
3. Build and open html in Chrome Version 71.0.3578.98 (latest version)

https://deck.net/f3d5ac5a0f2493f6c6b5a511688fd20f

### Expected Result
On Bridge console:
```js
Absolute Top
Before Class is defined
After Class is defined
Startup
Absolute Bottom
```

### Actual Result

No bridge console output, chrome inspector console shows:
```js
Absolute Top
bridge.console.js:314
Uncaught TypeError: Cannot read property 'appendChild' of null
    at ctor.init (bridge.console.js:314)
    at new ctor (bridge.console.js:215)
    at Function.get [as instance] (bridge.console.js:22)
    at Function.logBase (bridge.console.js:90)
    at Function.log (bridge.console.js:129)
    at Function.System.Console.WriteLine (bridge.console.js:47)
    at App.cs:28


bridge.console.js:314
Uncaught TypeError: Cannot read property 'appendChild' of null
    at ctor.init (bridge.console.js:314)
    at new ctor (bridge.console.js:215)
    at Function.get [as instance] (bridge.console.js:22)
    at Function.logBase (bridge.console.js:90)
    at Function.error (bridge.console.js:122)
    at bridge.console.js:83
```

**Comment by geoffreymcgill** [comment] 2019-01-25 05:54
Hi @JonnyS7G – Can you post a copy of the .html file you are using?

Everything looks fine so far with what you have posted here.

**Comment by miladsadeghi72** [comment] 2019-01-25 13:58
hi @JonnyS7G and @geoffreymcgill 
i saw and test it
i really don't know this is a bug or not
but if you move script tags from head to body then it's working fine

in fact dect.net use that scripts in her body, not head
this exception when thrown the body element not declared

**Comment by JonnyS7G** [comment] 2019-01-25 14:33
Here is the html generated by visual studio. Yes, moving the script source to the body fixed the issue for me, thanks!

```html

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>InitTest</title>
    
    <script src="bridge.js"></script>
    <script src="bridge.console.js"></script>
    <script src="bridge.meta.js"></script>
    <script src="InitTest.js"></script>
    <script src="InitTest.meta.js"></script>
</head>
<body>
</body>
</html>

```

**Comment by geoffreymcgill** [comment] 2019-02-14 00:33
> in fact dect.net use that scripts in her body, not head

Deck.NET places the script tags in the `<head>` of the document.

I'm going to close this issue as I was unable to reproduce and the Deck.NET sample is working as expected, but please feel free to follow-up with new information if you can provide a reproducible sample and we will re-open the issue.

**Closed by geoffreymcgill** 2019-02-14 00:33 UTC
