### ISSUE TITLE
Lots of red squiggles in VS using Bridge (System.Void not defined, dupe references between Bridge+mscorlib)

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#419] opened 2015-09-04 13:09 UTC
Many of my colleagues have reported this to me for a while, but I hadn't really seen it. Today, I'm seeing it, and I can't find any way to fix it.

We have a bunch of Bridge code that works, but VS reports lots of errors (mostly `Predefined type 'System.Object/Void' is not defined or imported`, but also some types defined in multiple places). There are no references to any MS `System` assemblies (screenshot includes reference below).

The repo I'm building is available here:
https://bitbucket.org/DanRoberts/reactbridgedotnet

![Squiggles](https://cloud.githubusercontent.com/assets/1078012/9684284/78b79ff6-530e-11e5-8cc2-5a481c9f9507.png)

Note: The project "works", but finding real compile errors will be tricky like this!

**UPDATE** by @DaniilVeriga:
Confirmed to be a [bug](https://connect.microsoft.com/VisualStudio/feedback/details/1893825/targets-file-from-a-nuget-package-is-not-re-applied-to-the-project-after-nuget-restore) in Visual Studio by Microsoft team. They are looking to fix in the next major version of VS (after 2015).

**Comment by DanTup** [comment] 2015-09-04 13:21
Changing the dropdown in the error list from "Build + Intellisense" has fixed this for me, but sadly not for my colleagues (even restarting VS after making the change has not fixed it for them).

**Comment by LeonidVeriga** [comment] 2015-09-04 16:57
Can you please confirm that is correct - you use:
 - VS2015
 - Bridge 1.7 from NuGet

**Comment by DanTup** [comment] 2015-09-04 17:09
I believe that is correct. I'll check for sure on Monday, but we deliberately set the version of the builds from our own build server to 9.x to avoid any confusion (and so it couldn't be picked by the version resolution for a default NuGet install, which I believe is set to 1.x).

(It also randomly fixed itself for me, without any removal/reinstalling of the package).

The *build* step seems fine; so I don't think the MSBuild output will help at all. It seems to be entirely isolated to the editor and the "Intellisense" part of the Error List. I made some minor tweaks to code and pushed them, and the issue disappeared from my colleagues machines too. And then on another project, they still have it :(

I wonder if something in the code is causing the editor to load mscorlib... Will continue to investigate and see if we can track it down. If you can't repro using the repository linked above, let me know, and I'll try do some more testing on a smaller/cleaner repo and share that.

**Comment by fabriciomurta** [comment] 2015-09-04 17:11
Hello, I've just cloned your repo and opened with VS2013.5 Ultimate.
No squiggles.
Maybe... Can you try cloning your repo to a new folder and opening it on you VS?

**Comment by DanTup** [comment] 2015-09-04 17:25
> No squiggles.

Strange! I will do some more digging next week and try and post some more info. Most of my colleagues cloned the repo fresh when the had this (and tried various clean/rebuild combos). There wasn't an obvious pattern to it, but there must be something causing it!

> By the way, nice job! Long time since I last "mercurialed" ;]

Blame @productiverage for moving from GitHub to BitBucket when everyone else was going the other way! ;-)

We do have better React bindings now (using your `Element` classes for the attributes) but they still need some work; hoping to finish fleshing them out soon.

**Comment by fabriciomurta** [comment] 2015-09-04 17:27
An update: what I can reproduce here is this:
1. clone repo
2. open with visual studio
3. open `Bridge.React/Dispatcher/AppDispatcher.cs`
  No error nor squiggles
4. build
5. Success. But now intellisense will complain about multiple referenced names (in both bridge and mscorlib)
6. Unload project + reload
7. rebuild, open AppDispatcher (from step 3), no more squiggles no matter what.

After saving and closing the project, I see no changed files so it seems VS2013 is NOT trying to "fix" something that VS2015 could have broke.

The actual issue you reported was not reproducible. Only squiggles shown were due to double references (rogue mscorlib ref).

**Comment by DanTup** [comment] 2015-09-07 08:11
Ok, we see the same behaviour here... Unloading and reloading the project causes all the errors to disappear :)

Any thoughts on why this rogue mscorlib reference might be appearing on first load?

**Comment by vladsch** [comment] 2015-09-07 14:19
I guess it can be related with the following condition `Condition="Exists('..\packages\Bridge.1.7.0\build\Bridge.targets')"` in 
`<Import Project="..\packages\Bridge.1.7.0\build\Bridge.targets" Condition="Exists('..\packages\Bridge.1.7.0\build\Bridge.targets')" />`

On first load, there is no Bridge files from Nuget. If you start a build then VS downloads Bridge files but doesn't recalculate condition and import statement is not applied still. But when you reload project (and Bridge files already exist) then condition is true and statement is applied

If Bridge Nuget files will exist on first load then you will not see any issues

**Comment by DanTup** [comment] 2015-09-07 15:22
> If Bridge Nuget files exist on first load then you will not see any issues

I'm sure we still see it even after full Rebuild then Restart VS, but will do some more testing...

**Comment by DanTup** [comment] 2015-09-11 12:45
Ok, we can't reproduce other than without the packages folder as described above. We're confused, because we're sure we saw the issue persist across build/VS restarts last week, but since we can't repro, I think we can assume the info above is correct.

**Comment by DanTup** [comment] 2015-09-25 13:01
We've just been seeing this again on some new dev machines... No amount of restarting VS and cleaning/rebuilding solved it, but unloading/reloading project did fix it again.

I can't figure out why unload/reload fixes it, but reopening VS (even when the packages have been restored) doesn't! :(

**Comment by DaniilVeriga** [comment] 2015-09-25 16:07
I am going to investigate in details and if I get it reproducible consistently with a basic project, I'll report to Microsoft. It looks to be a VS defect.

**Comment by DaniilVeriga** [comment] 2015-09-26 08:40
By the way, the same issue happens with Saltarelle that has been acquired by Bridge. This fact sort of proves that is likely a VS issue, rather than something else.

**Comment by DanTup** [comment] 2015-09-26 16:32
Yeah, I think it's a VS issue too... If you raise on Connect or GitHub, please post a link here. Unload/reload is a reasonable workaround for now, but in a large project might become a pain (unless there's an easy way to unload/reload all).

**Comment by DaniilVeriga** [comment] 2015-10-12 12:12
Submitted a [feedback item](https://connect.microsoft.com/VisualStudio/feedback/details/1893825/targets-file-from-a-nuget-package-is-not-re-applied-to-the-project-after-nuget-restore) to Microsoft. I am sorry for the delay.

**Comment by DanTup** [comment] 2015-10-12 16:43
Thanks; I've upvoted and clicked "I can repro" too :)

**Comment by DaniilVeriga** [comment] 2015-10-12 17:12
That is highly appreciated, thank you! Hopefully, we'll see soon what Microsoft thinks about it.

**Comment by DaniilVeriga** [comment] 2015-10-29 13:30
After an initial follow-up "we are reviewing" Microsoft keeps silent so far. I posted a bump a few days ago, but nothing yet.

**Comment by DanTup** [comment] 2015-10-29 14:13
I tweeted the Connect link to @Pilchie and got this response:

> @DanTup my team owns, but the design of the current project system makes it hard. We're looking to fix in next major VS. cc @davkean
https://twitter.com/Pilchie/status/659734263026200576

So it seems like a fix might be some way off :-(

**Comment by DaniilVeriga** [comment] 2015-10-29 14:26
Thank you very much for that! Next major release... Yeah, it doesn't sound like soon:) But it is something at least. I hope to get an official update in the feedback item as well which we could use to mention the problem to Bridge developers in a Readme file. Though, maybe, that twitter post could be good enough.

**Comment by DanTup** [comment] 2015-10-30 09:25
I did enquire about whether it could be "fixed" by an extension that detects/auto-reloads, but no concrete answer. Might be something to explore if you're familiar with the VS SDK (I don't have much experience with it and it frustrates me every time I try to do something!).

**Comment by DaniilVeriga** [comment] 2015-11-03 09:43
I will try looking into that, but most likely we'll have to wait a fix. If I find out something, I'll post a follow-up.

**Comment by geoffreymcgill** [comment] 2016-02-23 04:34
Related to Issue #46

**Comment by davkean** [comment] 2016-02-23 16:02
These sorts of bugs occur because the project or targets is doing something that is breaking the design-time build. A design-time build is a cut-down build that occurs in the background to enable us to populate IntelliSense, if there are build errors, we can’t populate IntelliSense or background analysis.

Do the following to diagnose what's going on:

1)      Delete the .vs folder from the solution directory
2)      Open Developer Command Prompt for VS 2015
3)      At the prompt:
> SET TRACEDESIGNTIME=true
> devenv.exe
 
4)      In the Visual Studio instance that opens, open the problematic solution
5)      Close Visual Studio
6)      Look at %TEMP%\XXXX.designtime.log, this will contain MSBuild logs showing the errors that occurred in the background build.

**Comment by geoffreymcgill** [comment] 2016-02-23 16:07
Hi @davkean: Excellent tips. We will investigate right away.

**Comment by DaniilVeriga** [comment] 2016-02-24 07:13
Hello @davkean,

Regarding the steps. It is not enough to reproduce the problem just to open and close the solution. If do that, there is "Build FAILED." in the log and this:

> This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Bridge.1.11.0\build\Bridge.targets.

But it is not the case. The problem starts appearing if build the solution which causes restoring the Bridge NuGet package. So, the first design build fails because of the missed NuGet package. That is okay. I build the solution then. "Build Succeeded". The actual (not the "design") build. But the design build is probably failed, because there are red squiggles in the .cs file view (?). Looking into **%TEMP%\XXXX.designtime.log**, I see three .log files. The initial one (appearing just after opening the solution) with "Build FAILED" and two more (appearing after the first actual build) with this thing in both:

> Build succeeded.
    0 Warning(s)
    0 Error(s)

So, the design build actually fails (there are red squiggles), but it is somehow not shown in the log file?

===
Nevertheless, please clarify was the problem not confirmed to be a bug ([Connect Item](https://connect.microsoft.com/VisualStudio/feedback/details/1893825/targets-file-from-a-nuget-package-is-not-re-applied-to-the-project-after-nuget-restore), [Twitter Discussion](https://twitter.com/Pilchie/status/659734263026200576)) in VS, because of not applying a .targets file after NuGet package restore?

**Comment by geoffreymcgill** [comment] 2016-03-12 00:19
Just to add a little to the conversation, the red squiggles appear because `<NoStdLib>True</NoStdLib>` is not applied to the project. The `<NoStdLib>True</NoStdLib>` is not applied, because the **.tagets** file is not applied when NuGet refreshes the packages.

Still the same issue (.targets not applied), but finding a way to set `<NoStdLib>True</NoStdLib>` on the .csproj should solve this problem.

We are investigating.

**Comment by geoffreymcgill** [comment] 2016-03-12 07:17
During the installation process we've added the **NoStdLib** config to the .csproj file. 

```xml
<PropertyGroup>
  <NoStdLib>true</NoStdLib>
</PropertyGroup>
```

A temporary feature [branch](https://github.com/bridgedotnet/Bridge/tree/Issue419) has been created if you want to test. Rebuild the project in **Release** mode, then point your NuGet Package Manager to the **bin/Release/** folder to install. See [Local NuGet Packaging](http://bridge.net/bridge-1-11-released/) for more information on building locally and installing from a local NuGet package. 

One downside of this approach is Visual Studio will prompt to reload the project. Just click **Reload**.

<img width="573" alt="screenshot 2016-03-12 00 12 19" src="https://cloud.githubusercontent.com/assets/62210/13721514/1c608f74-e7e7-11e5-93fc-c172d4e2b3b7.png">

I'm not convinced this is the best solution to the squiggles problem, but it works. Some feedback would be appreciated.

**Comment by geoffreymcgill** [comment] 2016-03-12 07:45
In an attempt to not lose this script, here's an option for adding the **NoStdLib** config to all **PropertyGroups**. 

```
# Add NoStdLib to each PropertyGroup foreach
foreach($groups in $projectMSBuild.PropertyGroups){
	$groups.AddProperty('NoStdLib', 'true')
}
```

**Comment by DaniilVeriga** [comment] 2016-03-28 21:05
Finally, a fix with `NoStdLib` in .csproj has been merged to the master branch and it will go to 1.12.

Though, not to lose a track of the VS bug, created #1113.

**Comment by DanTup** [comment] 2016-03-28 21:18
Sounds good; will let you know if we see this at all after 1.12 :)

**Comment by DaniilVeriga** [comment] 2016-04-13 14:16
The problem has been discussed again in [this thread](http://forums.bridge.net/forum/bridge-net-pro/bugs/1754). The issue can be still reproducible in some scenarios.

As of 1.12 we add `<NoStdLib>true</NoStdLib>` into a .csproj file and it fixes the problem at some extent, but:

1) `<NoStdLib>true</NoStdLib>` is included in .csproj only with a fresh Bridge 1.12 installation. If you `Update-Package Bridge` from 1.x to 1.12, `<NoStdLib>` is not included into .csproj and the issue can be reproducible. In such cases you can re-install Bridge: `Uninstall-Package Bridge` and then `Install-Package Bridge`. Or you can add `<NoStdLib>` setting and others (see bellow) into .csproj manually.

2) `<NoStdLib>true<NoStdLib>` is only included into a current Build Mode .csproj settings which is set during a Bridge installation. For example:
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  <NoStdLib>true</NoStdLib>
  ...
```

So, if you switch from Debug to Release Build Mode, the issue might be reproducible again.

We have to correct it and add `<NoStdLib>true</NoStdLib>` into general .csproj settings regardless the Build Mode. We'll try to patch it up in 1.12.1.

3) `<NoStdLib>true<NoStdLib>` is not the only setting which has to be moved from `Bridge.targets` to a `.csproj` file. Even with `<NoStdLib>` in .csproj the issue can be reproducible. These two settings have to be added to .csproj as well:

```
<AddAdditionalExplicitAssemblyReferences>false</AddAdditionalExplicitAssemblyReferences>
<AdditionalExplicitAssemblyReferences />
```
We'll try to patch it up in 1.12.1 as well.

I am reopening the issue.

**Closed** 2016-04-15 20:22 UTC
Labels: defect, in progress

**Comment by LeonidVeriga** [comment] 2016-04-18 22:00
The key notes about the current `install.ps1` and `uninstall.ps1` state:

0. Prerequisites. All the hassle with `install.ps1` is because of the VS IntelliSense squiggles issue in NuGet Restore scenario. `Bridge.targets` is not re-applied after the NuGet Bridge package restore and it is officially confirmed as a bug by VS team (#1113).

It was discovered that having `NoStdLib`, `AddAdditionalExplicitAssemblyReferences` and `AdditionalExplicitAssemblyReferences` properties in .csproj helps with the Restore scenario.

1.The current `install.ps1` triggers a Reload dialogue on any new Bridge NuGet installation (`Install-Package Bridge` scenario) to ensure `NoStdLib`, `AddAdditionalExplicitAssemblyReferences` and `AdditionalExplicitAssemblyReferences` properties are applied by Visual Studio. A Reload is required to ensure the properties are applied and the VS IntelliSense squiggles issue is not reproduced.

2. We could not find a way to force reloading without a user having to click the [Reload button](https://github.com/bridgedotnet/Bridge/issues/419#issuecomment-195678720) 

3. Bridge Project Template .vsix installation is fine, because `NoStdLib`, `AddAdditionalExplicitAssemblyReferences` and `AdditionalExplicitAssemblyReferences` properties are predefined in the project template. So, it doesn't trigger a Reload dialogue.

4. `uninstall.ps1` has been removed. So, it doesn't remove `NoStdLib`, `AddAdditionalExplicitAssemblyReferences` and `AdditionalExplicitAssemblyReferences` properties from .csproj. It was done to help with the `Update-Package Bridge` scenario. `Update-Package` is `Uninstall-Package` + `Install-Package`. If we remove the properties from .csproj on `Uninstall-Package` and then add them back on `Install-Package`, a project Reload is again required to avoid the IntelliSense squiggles issue. A Reload dialogue on `Update-Package` may annoy users, so, it has been decided not to remove the properties from .csproj on `Uninstall-Package`and `Update-Package` is not triggerring a Reload dialogue.

5. We tested the NuGet Restore and other scenarios enormous amount of times and sometimes the same repro steps give the different behavior. That said, even with `NoStdLib`, `AddAdditionalExplicitAssemblyReferences` and `AdditionalExplicitAssemblyReferences` properties in .csproj the VS IntelliSense squiggles errors are sometimes reproducible - though, very rare with the current workaround. If reproduced then manual re-loading of the project is [required](http://forums.bridge.net/forum/bridge-net-pro/bugs/1754-nuget-packages-cause-squigglies-if-packages-built-against-two-versions-of-bridge?p=2026#post2026).

**Comment by LeonidVeriga** [comment] 2016-04-19 19:04
The problem mentioned [here](http://forums.bridge.net/forum/bridge-net-pro/bugs/2127) (when updating package and having a PowerShell error) is also fixed in 1.12.1:
```
Removing Reference to System.Core
This reference cannot be removed from the project because it is always referenced by the compiler.
At C:\Project\packages\Bridge.1.12.0\tools\install.ps1:10 char:9
+         $_.Remove()
+         ~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
```

**Comment by geoffreymcgill** [comment] 2016-05-02 00:46
The NuGet packages have been updated for Bridge 1.13. Some comments on the new package structure and features have been added to #419. 

https://github.com/bridgedotnet/Bridge/issues/1042#issuecomment-216084711

In order to work-around this red squiggles issue, we've created a new **Bridge.Clean** package.

The Bridge.Clean package needs to be run manually, and is not included with any other packages. The package only needs to be installed once, and can actually be uninstalled immediately after installing. Once installed the required changes have been set and no further package updates are required.

After installing **Bridge.Clean** the red squiggles issue will go away. NOTE: If you have installed Bridge 1.12.1 previously, you won't need to install **Bridge.Clean**, although it's still a good idea and will not hurt. 

```Install-Package Bridge.Clean```

Hope this helps.

**Comment by calcock** [comment] 2016-10-25 18:38
Hey, 

I've got great  news for you, you're going to be really surprised, just  take a look <http://three.tustinspine.com/lnqa/22>

Later, calcock

**Comment by DanTup** [comment] 2017-05-16 19:17
@davkean Do you know if this ever got fixed? The [Connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/1893825/targets-file-from-a-nuget-package-is-not-re-applied-to-the-project-after-nuget-restore) seems to be a 404 now!

**Comment by michaelcheers** [comment] 2017-07-04 09:58
@DanTup, you make a good point, that is really weird.

**Comment by davkean** [comment] 2017-07-04 10:03
The legacy project does not reload targets, and will not in the foreseeable future. The [new project system](http://github.com/dotnet/project-system) beginning in 15.3 will reload targets, we have a [roadmap](https://github.com/dotnet/project-system/blob/master/docs/repo/roadmap.md) that tracks enable the new project system for all project types.
