### ISSUE TITLE
Classes/sub-classes within a project are being output in the wrong order in JS

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2748] opened 2017-06-02 12:44 UTC
We're having an issue with classes being output in the JS before their subclasses are defined, causing errors at startup. I can see this has been raised before (#191, #883) but those cases seem to have been resolved a long time ago.

Working around it using `[Priority]` will be really tedious because there are so many classes in this project.

We don't have a small repro yet (we're working on it), but I thought it was worth raising a case in case you have any thoughts in the meaintime.

cc @Porl91

**Comment by vladsch** [comment] 2017-06-02 13:12
Can activate logging in bridge.json and check errors in the log?
Maybe topological sorting is failed, If it is true then you will see a message in log, like "Topological sort failed..."

**Comment by Porl91** [comment] 2017-06-02 13:23
```text
***\build\Bridge.Min.targets(18,5): warning : 2017-06-02T14:21:11:524 	Warning		Topological sort failed  with error System.InvalidOperationException: Sequence contains no matching element
***\build\Bridge.Min.targets(18,5): warning :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
***\build\Bridge.Min.targets(18,5): warning :    at Bridge.Translator.Translator.SortReferences()
```

**Comment by vladsch** [comment] 2017-06-02 13:34
It means that sorting cannot find a type (why?) which is added to sort graph (this line is failed https://github.com/bridgedotnet/Bridge/blob/master/Compiler/Translator/Emitter/Emitter.TypeHelpers.cs#L302).
To debug Bridge compiler we use sandbox application which run translation manually (like this https://github.com/bridgedotnet/Bridge/issues/1902#issuecomment-250591837).

I have to add graph node name to the log to understand which type is absent in collection.

**Comment by Porl91** [comment] 2017-06-02 13:58
[Example1.zip](https://github.com/bridgedotnet/Bridge/files/1047860/Example1.zip)

Here's a tiny repo - we think it's being caused by the shared project.

**Comment by DanTup** [comment] 2017-06-02 14:39
@vladsch We can actually repro this on a totally empty project, without shared projects. We're wondering if the fix for sorting assemblies may have broken it for classes? It seems that whenever we use the "beta2" build that @ProductiveRage did (for testing assemblies), we get this issue (though assemblies are now correct).

If we revert to the official beta, this problem goes away for classes, but then the assemblies can be ordered incorrectly?

**Comment by Porl91** [comment] 2017-06-02 14:39
[Example1.zip](https://github.com/bridgedotnet/Bridge/files/1047988/Example1.zip)

Scratch that, apologies - The issue doesn't seem to be caused by the shared project, as an empty project produces the same error (repro is attached).

**Comment by vladsch** [comment] 2017-06-02 14:42
Thanks for example, I am reviewing it.
I will post result here soon.

**Comment by vladsch** [comment] 2017-06-02 16:00
The latest code in master doesn't reproduce the issue.
I guess that the issue is fixed in the following commit
https://github.com/bridgedotnet/Bridge/commit/052111e6ddcd65051e56b0d38940a23d13f1ecd9
(in Translator.cs\GetParentAssemblies method)

**Closed** 2017-06-02 18:24 UTC
Labels: defect

**Comment by DanTup** [comment] 2017-06-02 19:03
@vladsch Great! Are you still planning a new beta release on Monday? If not, I'll speak with @ProductiveRage and we'll rebuild from master and try that. Thanks!

**Comment by geoffreymcgill** [comment] 2017-06-02 19:08
The plan is still to release **-beta2** on Monday. That is not a guarantee, but we will try our best.

**Comment by DanTup** [comment] 2017-06-02 19:13
@geoffreymcgill Sounds good. If you'd consider calling it -beta3 that would save me a load of effort clearing package caches all over the place from our temp build 😁
