### ISSUE TITLE
System.Text.Encoding support

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2984] opened 2017-07-22 23:33 UTC
https://msdn.microsoft.com/en-us//library/system.text.encoding(v=vs.110).aspx

**Comment by michaelcheers** [comment] 2017-07-23 12:47
Duplicate of #2804.

**Closed** 2017-08-22 23:36 UTC
Labels: feature

**Comment by geoffreymcgill** [comment] 2017-08-23 07:22
**System.Text.Encoding** support has been included in the **Bridge 16.2.0** release.
