### ISSUE TITLE
Regression on type serialization.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3066] opened 2017-08-20 03:00 UTC
It works in Bridge 16.0 but not in 16.1. It totally breaks our app...

### Steps To Reproduce

https://deck.net/b821cbc1ace5d9528260c3fbcdd4288c
https://dotnetfiddle.net/1QKLHl

```c#
public class Program
{
    public static void Main()
    {
        int id = 1;
        int top = 2;
        
        var options = new { Id = id, Top = top };
        
        string payload = JsonConvert.SerializeObject(options);
        
        Console.WriteLine(payload);
    }
}
```

### Expected Result

```
{"Id":1,"Top":2}
```

### Actual Result

```
{"Id":{},"Top":{}}
```

**Comment by geoffreymcgill** [comment] 2017-08-20 04:42
Hi @hardhub,

I apologise for this problem. We are working on it right now and we are planning to release a new build before Monday AM.

## See Also

* https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/27

**Comment by geoffreymcgill** [comment] 2017-08-20 17:09
Duplicate of https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/27 which has now been fixed.

**Closed by geoffreymcgill** 2017-08-20 17:09 UTC
Labels: duplicate

**Comment by geoffreymcgill** [comment] 2017-08-22 07:30
Fixed, and your original sample now works correctly in Deck. 
https://deck.net/b821cbc1ace5d9528260c3fbcdd4288c

Hope this helps.
