### ISSUE TITLE
Output encoding

### ISSUE THREAD

**Issue by danfma** [bridgedotnet/Bridge#376] opened 2015-08-20 17:05 UTC
The output should be in UTF-8 or we should have a configuration for the build to output in some specific encoding (eg. the word 'módulo' in portuguese is being written as M�dulo, in the generated JS code).

**Comment by geoffreymcgill** [comment] 2015-08-20 17:44
Thanks for the report. We are investigating.

**Comment by fabriciomurta** [comment] 2015-08-20 19:35
Hello, I couldn't reproduce the issue.
Here's the test I've just built:
test.html
```html
<!DOCTYPE html>
<html>
 <head>
  <meta charset="UTF-8">
  <title></title>
  <script type="text/javascript" src="bridge.js"></script>
  <script type="text/javascript" src="classLibrary1.js"></script>
 </head>
 <body>
  Hey, world.
 </body>
</html>
```

Class1.cs
```csharp
using Bridge.Html5;

namespace ClassLibrary1
{
    /// <summary>
    /// Testing Documentation
    /// </summary>
    public class Class1
    {
        [Ready]
        public static void Main()
        {
            Console.Log("Atenuação");
            var div = new DivElement()
            {
                InnerHTML = "Acentuação [" + Document.CharacterSet + "]"
            };
            Document.Body.AppendChild(div);
        }
    }
}
```

And the results I see on the page:
![bridge376-pageoutput](https://cloud.githubusercontent.com/assets/10730372/9393597/2bc53200-4759-11e5-83f5-96e412972e6f.png)

Can you ensure:
1. Your .cs file is in UTF-8 format (default for recent Visual Studio versions, and default for MonoDevelop as far as I know)
2. Your hosting (if not local) allows you to override the encoding header or has UTF-8 (not latin1) by default

**Comment by fabriciomurta** [comment] 2015-12-09 13:37
Hello, we didn't receive a response from you since last reply. Do you still reproduce on your side? If so, can you provide more information on how you are producing this issue?

**Comment by geoffreymcgill** [comment] 2015-12-14 19:22
This does not appear to be a defect. Closing.

**Closed by geoffreymcgill** 2015-12-14 19:22 UTC
Labels: question
