### ISSUE TITLE
Sum of items in a list of type decimal returns string

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#992] opened 2016-02-23 03:58 UTC
See related forum thread:

http://forums.bridge.net/forum/bridge-net-pro/bugs/1635-sum-of-items-in-a-list-of-type-decimal-returns-string

### Expected behaviour

A **Decimal** object should be returned

### Actual behaviour

A **String** object is returned

### Steps to reproduce the behaviour

http://live.bridge.net/#1625e138fd8634c66d0f

```csharp
[Ready]
public static void Main()
{
    List<decimal> items = new List<decimal>();
    items.Add(14.4833M);

    decimal result = items.Sum(b => b);

    Console.Log(Script.TypeOf(result));
}
```

**Comment by vladsch** [comment] 2016-02-23 07:35
I cannot reproduce with latest code

**Comment by vladsch** [comment] 2016-02-23 13:24
I guess it is fixed in https://github.com/bridgedotnet/Bridge/issues/922

**Comment by geoffreymcgill** [comment] 2016-02-23 16:47
I thought I was testing with **master**, but apparently not. 

I retested, and the sample above does appear to be working correctly. An `object` is returned.

**Closed** 2016-02-23 16:47 UTC
Labels: defect

**Comment by DaniilVeriga** [comment] 2016-02-24 06:07
I guess a unit test would be good to add.

**Comment by vladsch** [comment] 2016-02-24 12:22
Unit test for #922 is already created, it covers this issue

**Comment by DaniilVeriga** [comment] 2016-02-24 12:27
Yeah, I saw it is unit tested, but I rather meant to add the user's test case from the original comment as well.
