### ISSUE TITLE
System.DateTime.Date returns incomplete date objects that cause Equals() to throw exception

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#3757] opened 2018-11-01 12:01 UTC
Cannot use instance property 'Date' on System.DateTime. It seems that $clearTime doesn't populate kind and ticks causing it to throw exception.

### Steps To Reproduce

https://deck.net/b347ec5cb8266762cb3267c92ea892ea

```csharp
public class Program
{
    public static void Main()
    {
        var a = System.DateTime.Now.Date;
            var b = System.DateTime.Now;
            var c = System.DateTime.Now.Date;
			var bugCount = 0;
        
            Console.WriteLine($"a={a} b={b} c={c}");

            try {
                if (b.Equals(a)) 
                {
                    Console.WriteLine("[1] b should not be equal to a");
                    bugCount++;
                }
            } catch(Exception) 
            {
                Console.WriteLine("[2] equals throws exception");
                bugCount++;
            }
            
            try {
                if (a.Equals(b)) 
                {
                    Console.WriteLine("[3] a should not be equal to b");
                    bugCount++;
                }
            } catch(Exception) 
            {
                Console.WriteLine("[4] equals throws exception");
                bugCount++;
            }
            
            try {
                if (!a.Equals(c)) 
                {
                    Console.WriteLine("[5] a should be equal to c");
                    bugCount++;
                }
            } catch(Exception) 
            {
                Console.WriteLine("[6] equals throws exception");
                bugCount++;
            }

            Console.WriteLine($"ended {(bugCount == 0 ? "successfully" : "with bugs")}");       
    }
}
```

### Expected Result

```js
ended successfully
```

### Actual Result

```js
[2] equals throws exception
ended with bugs
```

**Comment by fabriciomurta** [comment] 2018-11-01 17:11
Hello, @d-p-y!

Thanks for the report! I could see your code works nicely in native dotnet: https://dotnetfiddle.net/1r0VMq

**Comment by fabriciomurta** [comment] 2018-11-24 21:59
Thanks again for the report and pull request! We've just finished reviewing and merging it to dev! Your fixes will make it the next Bridge version!

We always attach the Bridge version the issue is fixed in as the issue's milestone, so it should always show the exact version a closed issue had its fix integrated to.

**Closed by fabriciomurta** 2018-11-24 21:59 UTC
Labels: defect, in-progress
