### ISSUE TITLE
Revise default setting of fileNameCasing to use None

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2755] opened 2017-06-05 18:16 UTC
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#filenamecasing

Old default was CamelCase

```// Old
<script src="classLibrary1.js"></script>
<script src="classLibrary1.meta.js"></script>

// Revised
<script src="ClassLibrary1.js"></script>
<script src="ClassLibrary1.meta.js"></script>```

**Comment by michaelcheers** [comment] 2017-06-05 19:41
Duplicate of #1720.

**Closed** 2017-06-05 20:49 UTC
Labels: breaking-change, modified
