### ISSUE TITLE
Wrong Jquery restitution Ajax

### ISSUE THREAD

**Issue by ericpreisig** [bridgedotnet/Bridge#2798] opened 2017-06-13 20:18 UTC
Hello,
I'm new on the Bridge, but I faced down a weird bug (I guess).

I'm in visual studio. 
I added the Bridge.Jquery package, but when I try to compile a simple ajax code like this: 
```
 jQuery.Ajax(
                new AjaxOptions()
                {
                    Url = "ajax/getUser",
                    Cache = true,
                    Success = delegate (object data, string textStatus, jqXHR request)
                    {
                       Window.Alert(data.ToString());
                    }
                }
            );         
```

It compiles, but when I launch the index.html, I have an error "$.Ajax is not a function".
I looked a bit on my side, and I found out that the compiler writes "$.Ajax" but for it to work it should write "$.ajax", with a lowercase. Same for all the parameters into the ajax function.
So if I put everything in lowercase in the output file, it works, but it's obviously not the purpose. 
Do you guys have an idea?

Thank you 

by the way, it works fine on Deck.Net

EDIT : It seems to be a bug on the beta-2 only

**Comment by geoffreymcgill** [comment] 2017-06-13 22:06
Hi @ericpreisig,

Welcome to Bridge!

We'll run some tests and try to reproduce. 

Can you post the contents of your projects **bridge.json** file? A **.cs** file demonstrating the scenario you are testing would be helpful too.

**Comment by ericpreisig** [comment] 2017-06-13 22:19
Hi, 
I'm sorry but I don't have this version anymore, I downgraded and every thing worked great. 
What I can say is that I took the "For visual studio" on the download page of the official website. 
I didn't make any change on the bridge.json, so it's the starting one. 
And on the .cs file, there was only this piece of code on the main function. 
Sorry that I cannot provide the files. It least I hope it will help. But yeah, there was nothing fancy

**Comment by geoffreymcgill** [comment] 2017-06-13 22:39
I tried several different scenarios and installed the .vsix a couple different times, but was unable to reproduce the `Ajax` vs `ajax` issue.

I'll close this issue for now, but please feel free to post an update if the steps required to reproduce are found, and we'll reopen the issue.

**Closed by geoffreymcgill** 2017-06-13 22:39 UTC

**Comment by geoffreymcgill** [comment] 2017-06-16 05:13
I think I figured out where the problem is happening. There is a new [2.9.4-beta](https://www.nuget.org/packages/Bridge.jquery) package of **Bridge.jQuery** available for Bridge 16.

Run the following two commands in your NuGet Package Manager Console:

```
uninstall-package  bridge.jquery

install-package bridge.jquery -pre
```

Your projects root packages.config file should look something like the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Bridge" version="16.0.0-beta2" targetFramework="net452" />
  <package id="Bridge.Core" version="16.0.0-beta2" targetFramework="net452" />
  <package id="Bridge.Html5" version="16.0.0-beta2" targetFramework="net452" />
  <package id="Bridge.jQuery" version="2.9.4-beta" targetFramework="net452" />
  <package id="Bridge.Min" version="16.0.0-beta2" targetFramework="net452" />
</packages>
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4400-jquery-method-case-sensitive

**Comment by geoffreymcgill** [comment] 2017-06-16 05:16
This problem should resolve itself once the final releases (non -beta) of **Bridge 16.0.0** and **Bridge.jQuery 2.9.4** are published to NuGet.

Checking the **Include prerelease** checkbox in your **NuGet Package Manager** should also fix this issue.

<img width="513" alt="screenshot 2017-06-15 23 14 38" src="https://user-images.githubusercontent.com/62210/27212891-87239e2e-5220-11e7-99c7-2b41c4e7d118.png">

**Comment by ericpreisig** [comment] 2017-06-16 05:18
Thank you for your work ! I'll post if I find anything else

**Comment by eberzosa** [comment] 2018-12-29 10:52
Hi, I'm having this same issue with 17.6.0 and jQuery 2.9.3
