### ISSUE TITLE
Cannot read property '$is' of undefined [1.10 regression?]

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#651] opened 2015-11-26 15:25 UTC
I just tried upgrading a little demo project from 1.9 to 1.10, and I now get this error:

    Uncaught TypeError: Cannot read property '$is' of undefined

May be related to casting inside a `.Select()` or the `[Ignore]`s on the class with the implicit casts?

You can [repro this error on live.bridge.net here](http://live.bridge.net/#5ccfca1c51b09d959ffc) which is running 1.10.0. If you run the same code in 1.9, it seems to work fine.

Full code for convenience:

```
using System.Linq;

public class App
{
    [Ready]
    public static void Main()
    {
        var danny = new [] {
            new Danny(),
            new Danny()
        };
        
        var a = danny.Select(d => (ReactElementOrText)d).ToArray();
    }
}

public class Danny : ReactElement {
}

public class ReactElement {
}

[Ignore]
public sealed class ReactElementOrText
{
    private ReactElementOrText() { }
    [Ignore] public extern static implicit operator ReactElementOrText(string text);
    [Ignore] public extern static implicit operator ReactElementOrText(ReactElement element);
}
```

**Comment by vladsch** [comment] 2015-11-26 15:40
I am doubt that the same code will work in 1.9 because `ReactElementOrText` is not emitted (Ignore) and absent in client side (no javascript representation) therefore you cast to `undefined`
So, if class is marked as Ignore then you have to provide javascript representation manually

**Comment by DanTup** [comment] 2015-11-26 15:51
It definitely seems to do what we want in 1.9 (though whether we're doing something weird, I don't know). The JS generated in 1.9 is this:

        var messages = Bridge.Linq.Enumerable.from(this.getprops().messages).select(function (m) {
            return Bridge.React.StatelessComponent$1(BridgeExamples.Components.MessageItem.Props).op_Implicit$1((new BridgeExamples.Components.MessageItem(Bridge.merge(new BridgeExamples.Components.MessageItem.Props(), {
                message: m
            } ))));
        }).toArray();

In 1.10, it's this:

        var messages = Bridge.Linq.Enumerable.from(this.getprops().messages).select(function (m) {
            return Bridge.cast((new BridgeExamples.Components.MessageItem(Bridge.merge(new BridgeExamples.Components.MessageItem.Props(), {
                message: m
            } ))), Bridge.React.ReactElementOrText);
        }).toArray();

I can provide a small working VS2015 project for you to look at if it helps. We can easily change the code, if we understand what in 1.10 would achieve the same thing we had in 1.9.

**Comment by vladsch** [comment] 2015-11-26 16:03
Thanks, I will investigate difference between 1.9 and 1.10 generated script
At this moment, you can try to set `IgnoreCast` attribute for `ReactElementOrText` class

**Comment by DanTup** [comment] 2015-11-26 16:09
That seems to do the job, thanks!

**Comment by DanTup** [comment] 2015-11-26 16:18
While that fixes the repro above (because it didn't actually try to use the objects), it also doesn't do what 1.9 did, as the objects returned now aren't the same and cause:

    Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object
    with keys {_reactElement}). If you meant to render a collection of children, use an array
    instead or wrap the object using createFragment(object) from the React add-ons. Check
    the render method of `MessageList`.

Let me know if you want me to send you over a small project that illustrates the issue (works with 1.9, fails with 1.10).

**Comment by vladsch** [comment] 2015-11-26 16:49
For me, Bridge 1.9 gives the following script
```
var a = Bridge.Linq.Enumerable.from(danny).select(function (d) {
                return d;
            }).toArray();
```
I don't see that `op_Implicit` is invoked in 1.9
So, test project reproduces the issue will be great (vladimir at object.net)

**Comment by vladsch** [comment] 2015-11-27 14:28
Also, What about to set `[Name("Object")]` for `ReactElementOrText` instead `IgnoreCast`?

**Comment by vladsch** [comment] 2015-11-30 16:04
Related issue: https://github.com/bridgedotnet/Bridge/issues/664

**Closed** 2015-11-30 16:05 UTC
Labels: defect, question

**Comment by calcock** [comment] 2016-10-25 18:17
Hello! 

I've seen some extremely interesting  stuff, it seems just unbelievable, just take a look  <http://rinaldo.sumitvohra.me/lncow/2>


Yours truly, calcock

**Comment by DanTup** [comment] 2016-10-25 18:22
@calcock Have you been drinking or do you need to enable 2FA?!
