### ISSUE TITLE
Bridge 17.6.0 does not work in IE 11

### ISSUE THREAD

**Issue by kendallb** [bridgedotnet/Bridge#3827] opened 2019-01-20 00:19 UTC
I am testing bridge.net and using the latest NuGet package 17.6.0 and built the demo program. It works in all browsers I have tested except for Internet Explorer 11. 

### Steps To Reproduce

Load the any bridge.net app into the browser and it fails in the console with this (and more errors after this, but they could be cascading errors from the first one):

SCRIPT1046: Multiple definitions of a property not allowed in strict mode
bridge.js (14313,20)

It is failing on this line:

getItem: function (key) {

because both getItem and setItem appear to be defined twice for some reason?

**Comment by miladsadeghi72** [comment] 2019-01-20 06:38
in fact this is not a bug,
you can fix this by do flowing steps:
1-open bridge.js file
2-find and delete this code
```javascript 
       "use strict";
```

attention, if you rebuild the solution then use strict back again

**Comment by kendallb** [comment] 2019-01-20 06:55
So I would have to do that on every build? That's a bug IMHO. I would expect this to work out of the box even with crappy browsers like IE11?

**Comment by kendallb** [comment] 2019-01-20 18:36
I appreciate the comments. Unfortunate it’s not really possible to manually edit the JavaScript files generated on every build so we can test on IE11. Perhaps this should be an option in the bridge.json file?

**Comment by kcudnik** [comment] 2019-01-20 19:07
As a quick  workaround you can add post build step like sed substitution inplace to remove usestrict line

**Comment by geoffreymcgill** [comment] 2019-01-20 21:48
Hi @kendallb – Thanks for reporting this issue. I have marked as a defect and we'll do our best to fix for the next release.

**Comment by geoffreymcgill** [comment] 2019-01-20 21:50
@kendallb,

> Perhaps this should be an option in the bridge.json file?

Check out the `afterBuild` config of **bridge.json**:
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#afterbuild

Hope this helps.

**Comment by kendallb** [comment] 2019-01-20 22:41
Yeah I could potentially have something run in the after build process to fix it until it is fixed in the next release.

**Comment by ProductiveRage** [comment] 2019-01-21 16:13
I think that this and issue #3828 might both be caused by the generic sorted list class have two indexer properties and the compiler not handling that correctly (https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Collections/Generic/SortedList.cs).

**Comment by hardhub** [comment] 2019-02-01 21:44
> 
> 
> in fact this is not a bug,
> you can fix this by do flowing steps:
> 1-open bridge.js file
> 2-find and delete this code
> 
> ```js
>        "use strict";
> ```
> 
> attention, if you rebuild the solution then use strict back again

I think it is bug:
1) error in production environment
2) undesired behavior during property definition

But I like your idea as hotfix!

**Comment by geoffreymcgill** [comment] 2019-02-25 20:39
This issue has been fixed and the fix will be included in the upcoming Bridge 17.7.0 release.

**Comment by BojidarStanchev** [comment] 2019-03-01 14:58
When is 17.7.0 coming out?

**Comment by geoffreymcgill** [comment] 2019-03-01 22:29
@BojidarStanchev – The release status of 17.7 can be tracked in the following milestone:
https://github.com/bridgedotnet/Bridge/milestone/70

Once all issues in that milestone are closed, the release will be made shortly thereafter. Almost all the issues in 17.7 are now in the `in-progress` state which means they have been fixed and there are unit tests in place. Once a final review has been completed the related PR will be merged into the **master** branch and the issue closed.

I would anticipate this process being completed sometime before the end of March 2019.

Hope this helps.

**Comment by fabriciomurta** [comment] 2019-03-08 05:18
Fixed and merged upstream! The fix will make it to the next Bridge release (see attached milestone).

**Closed by fabriciomurta** 2019-03-08 05:18 UTC
Labels: defect, in-progress
