### ISSUE TITLE
`combineScripts: true` on a project that is referenced results in duplication of scripts and fails to load

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2976] opened 2017-07-18 11:16 UTC
Given 3 Bridge projects, `A`, `B` and `C`; `A` references both `B`+`C` and `B` references `C`. `combineScripts: true` is set for all packages.

The build output of `A` gets the JavaScript from `C` twice, once from its own reference and once from the combined scripts in `B`.

This results in an error when loading project A in the browser:

> Class `C.TestType` is already defined

I guess this is because C's JS is being combined  into B's before it then gets embedded in the assembly, and then is pulled out by A. This means currently it's not possible to use `combineScripts` on a project that gets referenced by another if there's a project referenced by both (this is really common with a library like Bridge.React).

It could be argued that we shouldn't use `combineScripts` in non-leaf node projects, however we need it in our production apps and we have test projects that need to reference those production apps.

I think the issue is related to combineScripts being used to create the JS on disk and that then embedded in the DLLs. I wonder if it would be possible to embed "clean" (non-combined) JS into the DLL regardless of the combineScripts setting? (It seems strange to be embedding things like Bridge.js and other dependencies JS inside a DLL).

**Comment by LeonidVeriga** [comment] 2017-07-20 15:44
@DanTup,

There was a bug introduced in 16.0.0-beta2 that Bridge included referenced project's resources into combined output. The issue is fixed in PR #2906 included into **16.0.0-beta5**:

> #### Resource fix
> By default (if not overridden in **bridge.json** file **resources** option), Bridge embeds only project output files (resources from referenced assemblies are excluded) - restored **15.7** behaviour. The bug was it embedded outputs from referenced assemblies like **bridge.js** from Bridge.dll etc.

Just FYI, if you are interested in how Bridge handles formatted and minified resources - https://github.com/bridgedotnet/Bridge/pull/2870#issuecomment-312876520

**Comment by DanTup** [comment] 2017-07-20 19:01
@LeonidVeriga Oh, cool; this solves a big problem for our testing. We'll give it a go next week with `beta5`! (cc @calcock)

**Comment by DanTup** [comment] 2017-07-24 15:30
@LeonidVeriga Had a quick test of this in beta5, but seems like the issue still exists, we're still seeing duplicated output.

I'll try and get a repro together tomorrow if you can't reproduce this... Basically we have Project A and Project B both referencing Bridge.React from NuGet. Project A also references Project B. Both projects have `combineScripts: true` and Project A ends up with a duplicated Bridge.React in its output JS.

**Comment by LeonidVeriga** [comment] 2017-07-24 15:35
@DanTup, thank for checking. Let me test this one more time. I'll let you know once it's finished.

**Comment by LeonidVeriga** [comment] 2017-07-24 18:30
Yes, @DanTup, sorry for being confusing, The fix mention earlier was related to resource embedding only. We did not change combineScript behavior in **16.0**.

Is it possible to use `"outputBy": "Project"` instead of `combineScripts` for projects A and B?

Alternatively, is it possible to exclude Bridge.React from PorjectA's combined output by using
```
"name": "Bridge.React js file name",
"extract:" false
```

**Comment by DanTup** [comment] 2017-07-24 19:13
@LeonidVeriga I don't think either of those would work well. The two projects are our main application (and therefore we want to combine everything into a single script so that we don't need to maintain a list of script tags) and a test project - the test project needs to reference the app project, and also uses combineScripts so that the test framework can load it as a single JS file.

As for excluding the files, it would be quite a maintenance nightmare having to remember to add the JS files of all dependencies (and knowing what they're called, etc.) across the entire tree (our dependency tree is quite big now, many layers deep).

The ideal solution would be that combineScripts only affects the files on disk, but not the files embedded in the DLL. I know currently the former is used as the latter so this might not be trivial but it seems to make sense logically - I'm not sure it'd ever make sense to embed a dependent libraries script, it should work like .NET (where you need all your dependencies dependencies in your output folder).

Is this feasible?

**Comment by LeonidVeriga** [comment] 2017-07-24 20:49
@DanTup, we think it is feasible:
- the combined output file will be a "full" combined file containing output from all referenced assemblies and the project output file itself;
- embedded resources will contain particular files (parts of the combined file). Being referenced in another project, these files will be checked (resource name/assembly name) if project output already contains a particular file to avoid duplicated output.

Unfortunately, it is a bit late to include this feature into **16.0** release. We will try to implement it in **16.1**.

**Comment by LeonidVeriga** [comment] 2017-08-31 18:02
@DanTup, PR #3102 with this feature implementation is submitted. It would be greate if you could check it out and leave your feedback (inside the PR comments).

**Closed** 2017-09-11 13:55 UTC
Labels: feature

**Comment by DanTup** [comment] 2017-09-11 14:36
@LeonidVeriga Apologies for lack of feedback, it turned out Chris was also away!

I'm back in the office today with a lot to catch up on, but I'll try and test it this week (if you've pushed it out in a beta or something, that will make it slightly easier for me, but no problems if not).

**Comment by LeonidVeriga** [comment] 2017-09-11 14:42
@DanTup, no problem! We are going to include the current implementation in **16.3**. Looking forward to your feedback.

**Comment by DanTup** [comment] 2017-09-13 09:28
@LeonidVeriga In a small repro the fix in 16.3 looks good to me 👍

I haven't been able to confirm it works in our main app yet, as we need to upgrade to 16.3 all the way through (including Bridge.React), but we'll do that in the next week or so and let you know if there are any issues still. Thanks!
